### ISSUE TITLE
doc contributing part is deprecated

### ISSUE THREAD

**Issue by proooooogiba** [fortio/fortio#1000]
At the contributing part of readme write following command: `gofumpt -s -w *.go` 
But it should be use: `gofumpt -w *.go`
Because at the doc of gofumpt said, that -s is hidden and used as default https://github.com/mvdan/gofumpt/blob/86bffd62437a3c437c0b84d5d5ab244824e762fc/README.md?plain=1#L27

**Comment by ldemailly** [comment]
thanks you can update the readme as part of your PR (or a different one, whichever you prefer)
