### ISSUE TITLE
smart default ports for grpc mode with http/https scheme

### ISSUE THREAD

**Issue by asadali** [fortio/fortio#162]
pointed out by @ldemailly 
> for the grpc mode
>  if no :port is specified but http:// prefix is there, use 80, if https:// is there, use 443

**Comment by danehans** [comment]
@ldemailly I thought [this](https://github.com/istio/fortio/blob/master/fgrpc/grpcrunner.go#L47) code addresses this issue? If grpc-secure mode is specified or https prefixes the grpcping destination, then tls is used.

**Comment by ldemailly** [comment]
the code doesn't set the port

**Comment by danehans** [comment]
OK, let me know if you approve of this approach:

1. Create a func called `AppendPort` in the `fnet` pkg that parses a string for http/https in the prefix and appends :443/:80 accordingly. The func returns the original string if it's not prefixed with http/https or is unable to parse the string.
2. Update the fgrpc.Dial func to call `serverAddr := fnet.AppendPort(serverAddr string)`.

**Comment by ldemailly** [comment]
the trick there is differentiate between `:` for port (http://grpchost:123) vs `:` from ip addresses (http://[::1]/) - for http fast client it's done that way indirectly: (through url parsing)
https://github.com/istio/fortio/blob/master/fhttp/http_client.go#L406-L407

I think the approach would be to parse as a url to not duplicate ipv6 escaping ?
