### ISSUE TITLE
not able to install stackdriver agent in k8s cluster nodes for monitoring purpose

### ISSUE THREAD

**Issue by kidiyoor** [fortio/fortio#163]
k8s cluster nodes are using "Container-Optimized OS from Google" images.  These Chromium OS image do not support Stackdriver agents. 

Can we change it to Debian or CentOS ? 

ref: https://stackoverflow.com/questions/39864240/how-to-install-stackdriver-monitoring-agent-in-google-container-vm-images

**Comment by ldemailly** [comment]
wrong repo ? did you mean to file an Istio issue ? please do to https://github.com/istio/issues/issues/new

**Comment by kidiyoor** [comment]
Oops :) right! 

https://github.com/istio/istio/issues/3813
