### ISSUE TITLE
fortio remote test URL shouldn't require the percentiles list

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#164]
it should get the same default list as the command line
(somehow I thought I fixed this already but it's not working at the moment, one gets
    "Percentiles": null
)
http://localhost:8080/fortio/?labels=Fortio&url=http%3A%2F%2Flocalhost%3A8080%2Fecho&t=3s&qps=1000&save=on&r=0.0001&load=Start

and in general minimize the required parameters

ps: it should also be possible to ask for no percentile maybe using &p=&... (empty p list)

**Comment by olimpias** [comment]
May I work on this?

**Comment by ldemailly** [comment]
sure, thx!

**Comment by olimpias** [comment]
Unfortunately, I will add unit tests for this task on friday. Also, @ldemailly  could you suggest me a task that I can work on after unit tests are done.

**Comment by olimpias** [comment]
I added tests at #207 PR

**Comment by ldemailly** [comment]
closing this despite the tests not done/merged yet
