### ISSUE TITLE
fortio UI for grpc results is misleading/incomplete

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#168]
Follow up from #152 

- results are missing
- shows "100% error" all the time
- shows undefined as the url

![screen shot 2018-02-28 at 9 56 28 pm](https://user-images.githubusercontent.com/3664595/36829084-44647e5a-1cd2-11e8-9027-7cf348175364.png)

**Comment by asadali** [comment]
ack. I had noticed the undefined string but failed to observe the 100% errors part. I will work on this.

what do you mean by results are missing?

**Comment by ldemailly** [comment]
thanks. the codes map doesn’t show on the page during the run (probably goes to stdout instead of out)

**Comment by ldemailly** [comment]
I'm fixing that last part in #173
