### ISSUE TITLE
user report: tests still running despite "stop"

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#171]
@andraxylia reported tests still running despite clicking the stop all

![screen shot 2018-03-02 at 10 51 07 am](https://user-images.githubusercontent.com/3664595/36916048-a5593cc4-1e07-11e8-9447-e2ace7eaa2f8.png)

1) [try to] reproduce/confirm

2) regression test + fix

**Comment by danehans** [comment]
I am trying to reproduce the reported issue. I start fotio server:
```
$ docker run --name fortio_server -p 8080:8080 -p 8079:8079 istio/fortio server -loglevel debug &
[1] 41056
$ 22:54:15 I logger.go:97> Log level is now 0 Debug (was 2 Info)
22:54:15 V stats.go:517> Will use [50 75 90 99 99.9] for percentiles
Fortio 0.8.1-pre grpc 'ping' server listening on [::]:8079
Fortio 0.8.1-pre https redirector server listening on [::]:8081
22:54:15 V uihandler.go:96> Using resources directory set at link time: /usr/local/lib/fortio
Fortio 0.8.1-pre echo server listening on [::]:8080
UI started - visit:
http://localhost:8080/fortio/   (or any host/ip reachable on this server)
22:54:15 I fortio_main.go:186> All fortio 0.8.1-pre 2018-03-20 22:32 0e1347b31d9eb6d190f29b81b2ee710697b6c6c3 go1.10 servers started!
```

I open 2 browser tabs to the Fortio UI (http://localhost:8080/fortio/). I start a 15s load test to: `http://localhost:8080/echo?delay=250us:30,5ms:5&status=503:0.5,429:1.5` from the 1st UI. I jump to the 2nd tab and click stop. This stops the run in the 1st tab, so I'm unable to reproduce the issue.

@andraxylia can you confirm that these are the steps to your issue?

**Comment by ldemailly** [comment]
as far as I know, it works so it's likely just a matter of confirming

the example andra had was an overnight test, so closing the browser window; the only way to stop those is to use the UI I've put in the description - let's just confirm that works; even if there is exactly 1 outstanding runs or more than 1

(and maybe reopening one's laptop may cause the url to be repulled thus a new test to be started; but that should still have both stopped using the above UI - if one clicks just the interrupt it won't stop both but only the last one)

**Comment by ldemailly** [comment]
pretty sure this was user error / not using "interrupt all" from the main page
