### ISSUE TITLE
flake/failure on circleci for linters

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#178]
https://circleci.com/gh/istio/fortio/550

WARNING: failed to make periodic_test.go a relative path: lstat periodic_test.go: no such file or directory
periodic_test.go:283::error: Test executed unexpected number of times 2 instead of 3 (test)

typically it actually seem to hide a different issue but... tbd

**Comment by ldemailly** [comment]
it's possible it's related to the bugs I am fixing in #173

**Comment by ldemailly** [comment]
could also be concurrency/a sub linter dying because of resource constraints;
might need to try a run with DEBUG_LINTERS="--debug --concurrency=2"

**Comment by ldemailly** [comment]
gometalinter --concurrency=2 \
--deadline=180s --enable-all --aggregate \
--exclude=.pb.go --disable=gocyclo --line-length=132 . ./ui ./log ./echosrv ./version ./fhttp ./periodic ./fnet ./histogram ./stats ./fgrpc
WARNING: failed to make httprunner_test.go a relative path: lstat httprunner_test.go: no such file or directory
httprunner_test.go:81::error: Number go routine before test 35 (test)
Makefile:36: recipe for target 'local-lint' failed


https://circleci.com/gh/istio/fortio/575

**Comment by danehans** [comment]
I see a similaar error running `make lint`:
```
$ make lint
Checking that Gopkg.* are in sync with vendor/ submodule:
if this fails, 'make pull' and/or seek on-call help
diff Gopkg.toml vendor/
diff Gopkg.lock vendor/
docker run -v /Users/daneyonhansen/code/go/src/istio.io/fortio:/go/src/istio.io/fortio istio/fortio.build:v6 bash -c \
		"cd fortio && time go install . ./echosrv ./fgrpc ./fhttp ./fnet ./histogram ./log ./periodic ./stats ./ui ./version \
		&& time make local-lint LINT_PACKAGES=\". ./echosrv ./fgrpc ./fhttp ./fnet ./histogram ./log ./periodic ./stats ./ui ./version\""

real	0m5.083s
user	0m7.520s
sys	0m2.480s
gometalinter  \
--deadline=180s --enable-all --aggregate \
--exclude=.pb.go --disable=gocyclo --line-length=132 . ./echosrv ./fgrpc ./fhttp ./fnet ./histogram ./log ./periodic ./stats ./ui ./version
WARNING: failed to make httprunner_test.go a relative path: lstat httprunner_test.go: no such file or directory
httprunner_test.go:81::error: Number go routine before test 36 (test)
Makefile:36: recipe for target 'local-lint' failed
make: *** [local-lint] Error 1

real	1m0.159s
user	1m8.340s
sys	0m49.960s
make: *** [lint] Error 2
```

**Comment by ldemailly** [comment]
do make test first maybe

**Comment by ldemailly** [comment]
is that from master ? it's great if it reproes for you can you run it with DEBUG_LINTERS="--debug --concurrency=2" ?

**Comment by danehans** [comment]
I ran `make test` first. After the above error, I ran `make lint` again and the process completed without error. I ran `make lint` a 3rd time and the same error returned. This was against master. I have tried again this morning and I am not seeing the error. I will update this issue if i see the error again.

**Comment by ldemailly** [comment]
another
periodic_test.go:267::error: Test executed unexpected number of times 13 instead of 9-12 (test)

will relax some constraints but I think I need to mark the tests as serialized
