### ISSUE TITLE
outbound payload option

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#187]
we have size= for echo, but client side payload in addition to existing grpc one would be good

originally from #2

**Comment by olimpias** [comment]
Hi @ldemailly  . May I work on this task?

**Comment by ldemailly** [comment]
it’s a subset of or maybe just a dup of #260 

can you write up how first?

**Comment by olimpias** [comment]
Sorry, I was confused. I thought that the task was asking for adding size to PingMessage to provide payload from server side in GRPC. But I can still look for #260 and share my suggestion for a solution, If you are not working on it.

**Comment by ldemailly** [comment]
I’m on leave so in theory not working

for grpc there is -payload but it takes an inconvenient string, probably could be ˋ-payload-size int` in addition for random payload of given size

**Comment by olimpias** [comment]
To add payload-size support, I will need to move some methods from http_server and http_util to network file  for reusing. The reusable methods  are `ChangeMaxPayloadSize` and `generateSize`. Is that okay to you?

**Comment by ldemailly** [comment]
yes sounds good, thanks

**Comment by ldemailly** [comment]
grpc part is done in #270

**Comment by olimpias** [comment]
Hi @ldemailly , I think this is done with #273. Should we close it?

**Comment by ldemailly** [comment]
yes thanks !
