### ISSUE TITLE
TestProxy Test Flake

### ISSUE THREAD

**Issue by danehans** [fortio/fortio#214]
I am seeing the following flake with the TestProxy test:
```
Fortio 0.8.1-pre proxy for [2607:f8b0:4007:80c::2004]:80 server listening on [::]:58265
11:53:45 V network.go:148> Proxy: Accepted proxy connection from 127.0.0.1:58266 for [2607:f8b0:4007:80c::2004]:80
11:55:00 E network.go:120> Proxy: unable to connect to [2607:f8b0:4007:80c::2004]:80 for 127.0.0.1:58266 : dial tcp [2607:f8b0:4007:80c::2004]:80: getsockopt: operation timed out
	network_test.go:135: read error with proxy: EOF
	network_test.go:140: Unexpected reply '""', expected starting with '"HTTP/1.0 200 OK\r\n"'
```

The error is occurring because the proxy is using an IPv6 address for the test destination (www.google.com). After further inspection, I see the `Resolve` function selects the first TCP address returned by `net.LookupIP(host)`. This code is assuming that an IPv4 address will be the first address in the `[]net.IP`.

**Comment by ldemailly** [comment]
> After further inspection, I see the Resolve function selects the first TCP address returned by net.LookupIP(host). This code is assuming that an IPv4 address will be the first address in the []net.IP.

I don't think so.

the issue is ipv6 isn't working on your machine ?

ie if you do `fortio curl www.google.com` it will fail too

**Comment by danehans** [comment]
For some reason the test is no longer flaking for me. I am able to `fortio curl www.google.com`. As you mention, maybe my IPv6 was flaking with my ISP.
