### ISSUE TITLE
man page is missing

### ISSUE THREAD

**Issue by thanasisk** [fortio/fortio#245]
Hi all,

while README.md has extensive documentation, as far as I looked, there is no man page for man(1). If there is enough interest, I can commit to create and, more importantly, maintain a man page.

Please let me know

**Comment by ldemailly** [comment]
That would be great. have a look at release/updateFlags.sh for how I keep the readme in sync with the binary

**Comment by ldemailly** [comment]
Still up for this @thanasisk ? #306

**Comment by ldemailly** [comment]
close this in favor of #306
