### ISSUE TITLE
.deb/.rpm files for easier installation

### ISSUE THREAD

**Issue by thanasisk** [fortio/fortio#246]
Hi all,

while you provide a zip file, I think a nice addition would be to provide .deb/.rpm files. If there is enough interest, I can hack a script around fpm (for a start) that can provide these formats. Additionally, if my issue with man page gets accepted, it can be packaged there as well.

Please let me know your thoughts.

**Comment by ldemailly** [comment]
Sgtm ! Thanks !

**Comment by ldemailly** [comment]
#252 should make it easier to create proper packages

**Comment by ldemailly** [comment]
@thanasisk ping ? the new `make official-build` should make it really easy to build binaries for packages.

I will look into it if you can't - specifically the highest priority would be to be able to `apt-get install fortio`

**Comment by thanasisk** [comment]
pong - on it!

**Comment by ldemailly** [comment]
couple of links:

https://www.debian.org/doc/manuals/maint-guide/
http://packaging.ubuntu.com/html/
https://wiki.debian.org/HowToPackageForDebian

maybe also
https://github.com/Debian/dh-make-golang
