### ISSUE TITLE
Support authentication

### ISSUE THREAD

**Issue by ymesika** [fortio/fortio#256]
Something like a new `-user username:password` for http load tests.

**Comment by ldemailly** [comment]
it's quite involved if supporting all the possible modes (and for the super basic one it can be done using -H)

**Comment by ymesika** [comment]
Correct, your could but then you need to put there b64 encoding of that pair and google the correct header key and value format. Or, you could simply pass in an arg ;-)

**Comment by ldemailly** [comment]
`fortio curl -H "Authorization: Basic $(echo user:password|base64)" host:port` should work for now

**Comment by ldemailly** [comment]
I don't mind looking into adding better support - just not super high pri

**Comment by olimpias** [comment]
After 258 PR, may I work on this?

**Comment by ldemailly** [comment]
Sure but let’s discuss how before you write a lot of code or add any dependencies

**Comment by olimpias** [comment]
Okay. Give me a day to look at the code. I will give my comment about how I can write and add dependency. Then I will wait for your feedback comment to start impl. or continue to search.

**Comment by olimpias** [comment]
Here is my proposal, I'm going to add a userFlag to commonflags.go where expected input will be username:password format. I will carry userFlag on HTTPOptions by calling user as property name. In the InitHeaders method, I will check HTTPOptions's user property. If the value is not empty, I will add authentication header. I'm planning to use base64.StdEncoding.EncodeToString dependency to encode user:password. What do you think?

**Comment by ymesika** [comment]
@olimpias can we have it a curl-like flag?
I.e. `-u, --user <user:password> Server user and password`

**Comment by olimpias** [comment]
I haven't seen any example with double dash but `-user <user:password>` probably be okay. I hope its work for you.

**Comment by ldemailly** [comment]
yes I sort of try to follow some of the curl command line option choices so `-user USER[:PASSWORD]` like curl is good; I don't think that option is so frequent/useful as to use the short `-u` for it (unlike what I did for -L for follow redirects for instance)

ps: basic auth is really not that useful but maybe it's a start

ps2: @olimpias accept the invite at https://github.com/istio/fortio/invitations so I can assign the issue to you

**Comment by olimpias** [comment]
@ldemailly I accepted. As you say, I'm going to start with basic for a start. I don't know much about other possible authentication types in http except digest auth. Which type of authentication are you suggesting for http to implement?

**Comment by ldemailly** [comment]
there are a bunch of schemes https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml 
but I'm not sure we really want to get into that - specially if they require a round trip as that makes it hard to get performance data (and it's also something the envoy proxy would do for the app instead of backed into the client)

**Comment by olimpias** [comment]
I see your point. As far as I know digest auth requires round trip. So, should I start for basic authentication or wait for final decision about auth in general ? :)

**Comment by ldemailly** [comment]
let's just have the simple base64 short cut above for now

**Comment by ymesika** [comment]
Thanks @olimpias !
