### ISSUE TITLE
question about grpc load/performance test

### ISSUE THREAD

**Issue by thinkerou** [fortio/fortio#263]
first I have read https://github.com/istio/fortio#example-use-and-output, but I still have some question about grpc performance/load test:

- I am using `gatling + gatling-grpc` and `jmeter` for my grpc server load test

- And I have the following case: 

  - grpc A returns x
  - grpc B use x as its input
  - ...

question: fortio can also do like this? thanks a lot!

**Comment by ldemailly** [comment]
not sure what you meant by “grpc B uses x as input”

fortio load -grpc does exercise as a client a grpc health or ping server, the fortio ping server uses the input to echo ot back

**Comment by thinkerou** [comment]
@ldemailly sorry, my mean is: `rpc A(inputA) outputA` and `rpc B(inputB) outputB`, when load test I will first call `rpc A` which will returns `outputA`, and then call `rpc B` which will use `outputA` as its `inputB`.

**Comment by ldemailly** [comment]
ah sorry fortio default grpc client makes a single call, you could use the « runner » api and write custom go code to exercise your 2 services at once

**Comment by thinkerou** [comment]
@ldemailly thank you for replying!

**Comment by ldemailly** [comment]
most welcome. we do have plans to support fan out (#160) which relates to your question. closing this for now.
