### ISSUE TITLE
Delay is capped at 1.5 second without mention

### ISSUE THREAD

**Issue by thbar** [fortio/fortio#272]
Thanks for fortio, which I'm using to compare stacks - it's a great tool!

Something took me a bit by surprise, which is that the `delay` parameter is set to 1.5 second if I put it to anything higher.

The code seems to confirm that:
* https://github.com/istio/fortio/blob/cdb21807bcf3b2b83b94aba311d1a58d5c4ea311/fhttp/http_utils.go#L345
* https://github.com/istio/fortio/blob/cdb21807bcf3b2b83b94aba311d1a58d5c4ea311/fhttp/http_utils.go#L364

I think having an error instead of capping out would be less surprising (just my opinion!).

**Comment by ldemailly** [comment]
yes the problem is how to communicate a warning clearly / noticeably

i guess we should make that max a flag. the reason for the relatively low current max is that it’s easy to clog up a server with a lot of waiting go routines with a large delay

**Comment by thbar** [comment]
@ldemailly thanks for the input! Just FWIW, I'm using this flag to simulate slow responding services (I'm benchmarking systems who talk to such slow responding services), so having something that follows the delay (rather than just a max flag) is really helpful to test out this type of scenario! (I guess it's more a side-feature though!).

**Comment by ldemailly** [comment]
note that you can easily change that max yourself in the meantime 

I don’t get why a flag for max would not work for you? (you could start a server with a max of say 1h or whichever very large maximum you would wish)
