### ISSUE TITLE
distributed load test for 100k+ QPS?

### ISSUE THREAD

**Issue by cobookman** [fortio/fortio#274]
Can Fortio use multiple nodes for running a load test of > 100k QPS.

Thanks!

**Comment by ldemailly** [comment]
It can do 500k on a single node already, for a big enough node, but yes multi node is in the roadmap too

**Comment by ldemailly** [comment]
this is tracked in #134

**Comment by ryanli-me** [comment]
@ldemailly How do you reach 500k on a single node? I'm running on a 72 core ec2 instance and I could only get 10k with `fortio load -qps 0 -t 30s http://127.0.0.1:8080/echo?delay=250us:30,5ms:5&status=503:0.5,429:1.5`

**Comment by ldemailly** [comment]
as I think is mentioned in the FAQ, use a much higher than default -c, for instance try -c 512

**Comment by ryanli-me** [comment]
Thanks! I did get to >400k qps. However, I don't think it's mentioned in the FAQ, only the `-qps 0` flag is mentioned

**Comment by ldemailly** [comment]
faq says « So for a production environment I recommend you use a lot more connections (and the higher your latency the higher the number of connections is needed to maximize throughput) - a good starting point would be 2-4x the number of cores. Or start with -c 32 at least. »

should I try to make it clearer ?

**Comment by ryanli-me** [comment]
Thanks!
