### ISSUE TITLE
fortio UI: add + button to add more custom headers

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#283]
fortio UI: add + button to add more custom headers

**Comment by SeriyBg** [comment]
Have submitted a PR for this issue.
Also a question: what is the reason for template file not to be formatted at all? It's hard to read it as it is now. I can format it this PR or as a separate PR if there are no reasons for it not to be formatted

**Comment by ldemailly** [comment]
do you mean some indentation?
as long as it doesn’t make the file much bigger, sure you can add some, a seperate PR is good for whitespace only changes

**Comment by SeriyBg** [comment]
Yeap, I was talking about indentation. Will submit the PR with indented files, should not change file size significantly.
