### ISSUE TITLE
Help Wanted: "Sleep Times" And "Sleep Falling Behind"

### ISSUE THREAD

**Issue by ihcsim** [fortio/fortio#310]
I am hoping to better understand the meaning and implication behind "sleep times" and "sleep falling behind". I know the [FAQ](https://github.com/fortio/fortio/wiki/FAQ#i-want-to-get-the-best-results-what-flags-should-i-pass) and this comment [here](https://github.com/fortio/fortio/issues/3#issuecomment-408110365) mention that it means the target system can't keep up with the qps.

But for example, given this run:
```
Starting at 2000 qps with 4 thread(s) [gomax 1] for 10s : 5000 calls each (total 20000)
06:32:09 W periodic.go:487> T002 warning only did 4831 out of 5000 calls before reaching 10s
06:32:09 I periodic.go:533> T002 ended after 10.000757967s : 4831 calls. qps=483.06338538949666
06:32:09 W periodic.go:487> T001 warning only did 4834 out of 5000 calls before reaching 10s
06:32:09 I periodic.go:533> T001 ended after 10.002968142s : 4834 calls. qps=483.2565625899801
06:32:09 W periodic.go:487> T003 warning only did 4824 out of 5000 calls before reaching 10s
06:32:09 I periodic.go:533> T003 ended after 10.002987326s : 4824 calls. qps=482.25593443084205
06:32:09 W periodic.go:487> T000 warning only did 4834 out of 5000 calls before reaching 10s
06:32:09 I periodic.go:533> T000 ended after 10.002999931s : 4834 calls. qps=483.2550268264118
Ended after 10.003010885s : 19323 calls. qps=1931.7
Aggregated Sleep Time : count 19323 avg -0.17339684 +/- 0.1135 min -0.35573174 max 0.00123202 sum -3350.54707
# range, mid point, percentile, count
>= -0.355732 <= -0.001 , -0.178366 , 92.47, 17868
> -0.001 <= 0 , -0.0005 , 93.85, 266
> 0 <= 0.001 , 0.0005 , 99.99, 1187
> 0.001 <= 0.00123202 , 0.00111601 , 100.00, 2
# target 50% -0.163932
WARNING 92.47% of sleep were falling behind
```

What does the aggregated sleep time with its avg, negative min, max and sum mean? Also, what about the 92.47% warning imply?

When comparing the performance of two Fortio echo servers in two different environments, with all else equal (qps, number of connections, machine type etc.), can I conclude that the one which experienced no sleep warnings are performing better than the one with sleep warnings? Thanks!

**Comment by ldemailly** [comment]
It means 92.47% of the time fortio calculated how long it needs to sleep between 2 requests to maintain the target 2000qps it was actually already behind and would have to sleep a negative time (it can't use a time machine so it just makes the next request right away instead in that case, but keeps track of how much falling behind which is the stats)

Yes if one system has the warning and another doesn't it's better not to have it but you should not really use a 2000qps if it can't

Specifically though it could just be you need more simultaneous connections to attain the 2000qps, this is mentioned in the FAQ as well:
https://github.com/fortio/fortio/wiki/FAQ#i-want-to-get-the-best-results-what-flags-should-i-pass

Try`-c 32` first

Also try `-qps 0` to see what your system can do without sleep time

**Comment by ihcsim** [comment]
Ah.. cool. So if my entire test runs for 10 sec, during 9.247 sec (92%) of that duration, Fortio had to do some calculation to determine the sleep interval, right? A sleep average of -0.17339684 means Fortio sleeps for an average of 0.1734 second, during that 10 sec?

**Comment by ldemailly** [comment]
no a sleep avg of -0.173 means it fell behind by 0.173 on average - 0.35573174 was the worst one (it missed the target qps by 0.355 seconds which probably correlate with your actual results which you omitted above (some calls take a long time making it miss the next call)

please do a run with -qps 0 (-1 in the web ui) for max qps and post the result

**Comment by ihcsim** [comment]
Thanks Laurent, for the explanation.

> please do a run with -qps 0 (-1 in the web ui) for max qps and post the result

As far as this issue is concerned, I'm only interested in understanding the definitions of _sleep_ and the _falling behind_ warning. Unless you are very interested in seeing the result with -qps 0, I don't mind closing this issue.

Ultimately, my goal is to let my team know, given -qps _q_ and -c _c_ (where _q_ and _c_ will be tuned as desired), we are seeing X number of _falling behind_ warnings in environment X and Y warnings in environment Y etc. So in a way, I do want to see those sleep warnings to determine which environment set-up is better for our system, if that makes sense.

Let me know if I can go ahead and close this issue.

**Comment by ldemailly** [comment]
The short version is the warning does mean the results are somewhat invalid (ie need higher -c or lower -qps)

Yes will close if it's clear.

**Comment by ihcsim** [comment]
👍 The [FAQ](https://github.com/fortio/fortio/wiki/FAQ#i-want-to-get-the-best-results-what-flags-should-i-pass) is already quite clear on tuning the -qps and -c options to get better results.

**Comment by ihcsim** [comment]
@ldemailly Sorry to add to this thread again, but just want to make sure I'm doing this right. Below is the log of one of my test runs; 0 qps and 32 over 30 seconds targeting a Istio-meshed echo server on GKE (n1-standard-1).

The qps comes out to about 2817.2. So should I repeat the test at 75% of that qps, over 5 minutes? Thanks! 

```
Fortio 1.3.1-pre running at 0 queries per second, 1->1 procs, for 30s: fortio-echo-1.benchmark-istio:8079
08:47:40 I grpcrunner.go:152> Starting GRPC Ping test for fortio-echo-1.benchmark-istio:8079 with 1*32 threads at -1.0 qps
Starting at max qps with 32 thread(s) [gomax 1] for 30s
08:48:10 I periodic.go:533> T002 ended after 30.000598743s : 2593 calls. qps=86.43160832265127
08:48:10 I periodic.go:533> T026 ended after 30.002248047s : 2660 calls. qps=88.66002293671391
08:48:10 I periodic.go:533> T013 ended after 30.002501184s : 2656 calls. qps=88.525952676786
08:48:10 I periodic.go:533> T007 ended after 30.002585917s : 2587 calls. qps=86.22590089923415
08:48:10 I periodic.go:533> T016 ended after 30.006012821s : 2644 calls. qps=88.11567254112386
08:48:10 I periodic.go:533> T030 ended after 30.006074364s : 2636 calls. qps=87.84887913103887
08:48:10 I periodic.go:533> T018 ended after 30.006091195s : 2684 calls. qps=89.44850505710795
08:48:10 I periodic.go:533> T019 ended after 30.006105697s : 2630 calls. qps=87.64882809377515
08:48:10 I periodic.go:533> T006 ended after 30.006120006s : 2652 calls. qps=88.38197006043129
08:48:10 I periodic.go:533> T012 ended after 30.006154563s : 2621 calls. qps=87.34874688781026
08:48:10 I periodic.go:533> T014 ended after 30.006168125s : 2621 calls. qps=87.34870740847055
08:48:10 I periodic.go:533> T020 ended after 30.006181432s : 2665 calls. qps=88.81503319705715
08:48:10 I periodic.go:533> T031 ended after 30.00619469s : 2602 calls. qps=86.71542749361532
08:48:10 I periodic.go:533> T004 ended after 30.006227751s : 2688 calls. qps=89.58140364412913
08:48:10 I periodic.go:533> T024 ended after 30.006242224s : 2640 calls. qps=87.98169328542043
08:48:10 I periodic.go:533> T028 ended after 30.006256331s : 2692 calls. qps=89.71462385392098
08:48:10 I periodic.go:533> T003 ended after 30.006281994s : 2668 calls. qps=88.91471460987697
08:48:10 I periodic.go:533> T023 ended after 30.006324775s : 2648 calls. qps=88.24806169551965
08:48:10 I periodic.go:533> T015 ended after 30.006339657s : 2624 calls. qps=87.44818694964891
08:48:10 I periodic.go:533> T005 ended after 30.006397169s : 2600 calls. qps=86.64818989618966
08:48:10 I periodic.go:533> T025 ended after 30.006411928s : 2616 calls. qps=87.18136664513766
08:48:10 I periodic.go:533> T010 ended after 30.006425688s : 2660 calls. qps=88.64767925570595
08:48:10 I periodic.go:533> T001 ended after 30.006438491s : 2641 calls. qps=88.01444399314933
08:48:10 I periodic.go:533> T021 ended after 30.006451827s : 2635 calls. qps=87.81444787913945
08:48:10 I periodic.go:533> T011 ended after 30.006481298s : 2616 calls. qps=87.18116509630079
08:48:10 I periodic.go:533> T000 ended after 30.006496129s : 2616 calls. qps=87.18112200616945
08:48:10 I periodic.go:533> T027 ended after 30.006508918s : 2662 calls. qps=88.7140855763846
08:48:10 I periodic.go:533> T009 ended after 30.006550693s : 2667 calls. qps=88.8805923508617
08:48:10 I periodic.go:533> T029 ended after 30.006567772s : 2645 calls. qps=88.14736893928023
08:48:10 I periodic.go:533> T022 ended after 30.00658213s : 2655 calls. qps=88.48058697580163
08:48:10 I periodic.go:533> T008 ended after 30.006595982s : 2669 calls. qps=88.94711021540223
08:48:10 I periodic.go:533> T017 ended after 30.007100081s : 2642 calls. qps=88.04582891609945
Ended after 30.007125711s : 84535 calls. qps=2817.2
Aggregated Function Time : count 84535 avg 0.011355781 +/- 0.005568 min 0.000689269 max 0.175324051 sum 959.960926
# range, mid point, percentile, count
>= 0.000689269 <= 0.0007 , 0.000694634 , 0.00, 1
> 0.0008 <= 0.0009 , 0.00085 , 0.01, 4
> 0.0009 <= 0.001 , 0.00095 , 0.02, 9
> 0.001 <= 0.0011 , 0.00105 , 0.04, 17
> 0.0011 <= 0.0012 , 0.00115 , 0.09, 41
> 0.0012 <= 0.0014 , 0.0013 , 0.20, 93
> 0.0014 <= 0.0016 , 0.0015 , 0.29, 80
> 0.0016 <= 0.0018 , 0.0017 , 0.36, 57
> 0.0018 <= 0.002 , 0.0019 , 0.44, 68
> 0.002 <= 0.0025 , 0.00225 , 1.06, 529
> 0.0025 <= 0.003 , 0.00275 , 1.78, 608
> 0.003 <= 0.0035 , 0.00325 , 2.46, 574
> 0.0035 <= 0.004 , 0.00375 , 3.44, 831
> 0.004 <= 0.0045 , 0.00425 , 4.61, 984
> 0.0045 <= 0.005 , 0.00475 , 5.28, 568
> 0.005 <= 0.006 , 0.0055 , 7.66, 2011
> 0.006 <= 0.007 , 0.0065 , 10.61, 2496
> 0.007 <= 0.008 , 0.0075 , 13.48, 2425
> 0.008 <= 0.009 , 0.0085 , 18.90, 4579
> 0.009 <= 0.01 , 0.0095 , 34.02, 12781
> 0.01 <= 0.012 , 0.011 , 72.39, 32440
> 0.012 <= 0.014 , 0.013 , 87.32, 12622
> 0.014 <= 0.016 , 0.015 , 92.08, 4026
> 0.016 <= 0.018 , 0.017 , 94.07, 1679
> 0.018 <= 0.02 , 0.019 , 95.03, 809
> 0.02 <= 0.025 , 0.0225 , 96.69, 1401
> 0.025 <= 0.03 , 0.0275 , 99.15, 2080
> 0.03 <= 0.035 , 0.0325 , 99.67, 444
> 0.035 <= 0.04 , 0.0375 , 99.76, 71
> 0.04 <= 0.045 , 0.0425 , 99.78, 25
> 0.045 <= 0.05 , 0.0475 , 99.80, 10
> 0.05 <= 0.06 , 0.055 , 99.92, 108
> 0.06 <= 0.07 , 0.065 , 99.93, 4
> 0.07 <= 0.08 , 0.075 , 99.93, 3
> 0.08 <= 0.09 , 0.085 , 99.94, 5
> 0.1 <= 0.175324 , 0.137662 , 100.00, 52
# target 50% 0.010833
# target 75% 0.0123494
# target 90% 0.0151244
# target 99% 0.0297035
# target 99.9% 0.0580986
Ping SERVING : 84535
All done 84535 calls (plus 32 warmup) 11.356 ms avg, 2817.2 qps
Successfully wrote 5773 bytes of Json data to /data/2018-11-22-084740_grpc_istio_0qps_30s_echo_1_9.json
```

**Comment by grinbvi** [comment]
First of all, it is clear that the maintainer can not explain it correctly. Secondly, increasing the amount of go routines leads to tons of errors. It is better stick to 8.
