### ISSUE TITLE
Unclear if http/2 is available/used

### ISSUE THREAD

**Issue by ahmetb** [fortio/fortio#336]
I don't see an option about http2, and since go http.Client by default uses http2 when available, I'm inclined to think http2 is used by default:

    10:59:59 W http_client.go:136> https requested, switching to standard go client

Is this correct? If so, how to force-downgrade to http/1.1+keepalive?

If not, is there a way to upgrade to http2?

**Comment by ldemailly** [comment]
- fortio when making grpc calls uses h2 (because that's what grpc does)

- fortio built in fast http client uses http 1.1 (or 1.0 when specifying `-http1.0`)

- fortio standard go client uses what it uses - which unless it changed in recent go version (and maybe it did, I haven't looked at the standard client after go1.8) is also 1.1 but if it auto upgrades to h2 then you can force the standard go client using `-stdclient`)

- (and TLS tends to negotiate h2 when possible, but I don't think non https request with std go client does)

**Comment by ldemailly** [comment]
and when I checked a while ago, h2c (ie h2 without tls) was not supported by the standard go client because brad didn't want to... not sure if that has since changed ?

either way, happy to add an option if there is one (and PR welcome too)

**Comment by ahmetb** [comment]
Hmm, h2c works fine as a supported protocol on Knative. I was able to use grpc-go client with explicit option to skip verification. That said, grpc-go probably doesn't use standard go http.Client?

Given go http.Client negotiates for h2 with https://, I wonder which one of these should be done:

- add an explicit flag to disable h2 (possible by editing the http.Client fields)
- just document/log that h2 is being used when it's used (this is probably only available in resp.Protocol)

**Comment by ldemailly** [comment]
h2c isn't happening by default.

I am in the process of adding h2c for server and then for client

**Comment by ldemailly** [comment]
h2c for server is done now (echo server, behind envoy for instance can be set as   `http2-fortio` service name and get end to end h2 (since v1.12)

**Comment by ahmetb** [comment]
Fantastic, thanks!

**Comment by weibohe** [comment]
> if it auto upgrades to h2 then you can force the standard go client using -stdclient)

Hi! I tried to force client side to use h2 with -stdclient, but from what i can from envoy access logs, the client is still using Http 1.1 
`[2021-03-10T00:31:36.519Z] "POST / HTTP/1.1" 200 - "-" 10 10 0 0 "-" "fortio.org/fortio-1.14.1"`

I did see that fortio server already supports http2.

Can we add a `-http2` option to force the fortio client to use http2? 

When -http2 is enabled, pass a `http2.Transport` [here](https://github.com/fortio/fortio/blob/v1.14.1/fhttp/http_client.go#L411-L417). You can use https://pkg.go.dev/golang.org/x/net/http2#ConfigureTransport to re-use the existing http1 transport 

Thanks in advance!

**Comment by ldemailly** [comment]
@weibohe sorry I missed your update (github some skips notifications)

this is working now (including demonstrated h2 bi directional streaming when using payload from stdin for instancce)
```bash
$ fortio curl -h2 http://localhost:8080/debug
13:02:43.186 I scli.go:107> Starting Φορτίο 1.57.3 h1:kdPlBiws3cFsLcssZxCt2opFmHj14C3yPBokFhMWzmg= go1.20.6 arm64 darwin
13:02:43.187 I H2 requested, switching to std client
Φορτίο version 1.57.3 h1:kdPlBiws3cFsLcssZxCt2opFmHj14C3yPBokFhMWzmg= go1.20.6 arm64 darwin echo debug server up for 1m55.6s on K6922C3FGJ - request from [::1]:54322

GET /debug HTTP/2.0

headers:

Host: localhost:8080
User-Agent: fortio.org/fortio-1.57.3

body:
```
do reopen if you find any issue
