### ISSUE TITLE
Add option to re-initiate connections after a set number of requests

### ISSUE THREAD

**Issue by mandarjog** [fortio/fortio#339]
At present we can run the load generator for a set amount of time or a certain number of requests.
I would like to a mode   `--reconnetRequests=1000` where fortio client will reconnect after `1000` requests. 

Use case: We are testing SDS cert rotation using an `https` fortio client (std client).
For cert rotation to be exercised fortio should reconnect periodically to fetch the new cert.
In absence of this the previously negotiated key material continues to be used.

**Comment by ldemailly** [comment]
In the meantime/workaround:

use `-n 1000` and add an outer loop

**Comment by ldemailly** [comment]
done in upcoming 1.34
