### ISSUE TITLE
benchmark go 1.8 vs 1.9

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#34]
before switching to 1.9 let's measure that it's same or better
(in term of fortio self qps - should be > 100k qps with the fast client, benchmark against the stdclient to see if it's gotten better)

cc @bochunz want to run / compare ?

**Comment by thanasisk** [comment]
I can do it, provided that I get some instructions. I have some VMs in the cloud that I can use, one with Golang 1.8 and one with Golang 1.9. If instructions are provided, I can present findings in this Wednesday's Performance and Scalability WG session.

**Comment by ldemailly** [comment]
Thanks a lot for offering ! Can you basically run fortio against itself:

fortio server &

fortio load -L "go 1.8" -a -c 24 -qps -1 -t 60s http://localhost:8080/echo
(or use the UI)

do it several times for 1.8 and 1.9 to check how stable the max qps is with each

let's say you find the max qps is around 20000 also then run with a slightly lower target qps
eg -qps 18000 and see if it can reach it with 1.8 and 1.9

check with top the cpu utilization of both client (which is our code) and server (which is the standard go http server) for 1.8 and 1.9

also possibly use longer -t to see any memory/GC effect (like -t 30min)

(-a auto saves the json and -L gives it a label so you can use `fortio report` to visualize/show them on wed)

**Comment by thanasisk** [comment]
Hi,
I missed today's session. I am working actively on the topic, including writing a new tool to help us with benchmarking. Expect a final update Sunday

**Comment by ldemailly** [comment]
cool! I'm curious what the new tool is ? I would think fortio self run is enough + maybe go standard benchmark ?

**Comment by thanasisk** [comment]
well, it is a Python3 script that automates the whole process, just written for my convenience. I will publish it under my repos.

On a slightly different topic, how can I deliver my findings? A google doc?

**Comment by ldemailly** [comment]
google doc is fine yes, or here in the issue - whichever works for you

**Comment by ldemailly** [comment]
@thanasisk I hope all is well, let me know what you found ?

ps: we may stick with 1.8 for a while just for wider compatibility but maybe ship the binaries built with 1.9+ if there is a benefit

**Comment by thanasisk** [comment]
@ldemailly all is well - I will post my findings tomorrow or Monday. Sorry for the delay but real life intruded a bit!

**Comment by ldemailly** [comment]
ping ?
I'm about to switch to 1.10 for builds so would be nice to have data

**Comment by ldemailly** [comment]
ping... looks like data would have been useful #202

**Comment by ldemailly** [comment]
ping ?

**Comment by thanasisk** [comment]
pong!
will do it over the weekend - I was busy with IRL :)

**Comment by thanasisk** [comment]
Hi again,
I did some runs comparing golang 1.10 with 1.9. All tests were done in an Azure VM (Standard_DS3_v2)
durations:
- 30 - 60 - 90 - 300 - 600 - 1800 seconds per run

I have not had a thorough look at the JSONs as of now, give me a day or two (depending on $DAYJOB / IRL load) to visualize them. Any tool recommendations welcome.

Btw, is there still a need to benchmark golang v1.8.7 ?

**Comment by ldemailly** [comment]
Thanks ! it'd be interesting to get 1.8.7 too

and you can use fortio itself to compare runs (just run `fortio report` in the directory you have the results in)

you can also attach the raw data to this issue

**Comment by thanasisk** [comment]
Please find attached the JSONs
[results.tar.gz](https://github.com/istio/fortio/files/2002186/results.tar.gz)
(take the v1.9 results with a slight grain of salt, not entirely sure if v1.9 or v1.10 fortio server was running)
I will keep the VM running for a day or so, in case you want me to repeat tests with different parameters - just let me know.

**Comment by ldemailly** [comment]
you can tell the version by visiting the /debug endpoint
for instance 
https://istio.fortio.org/debug

```
Φορτίο version 0.9.0 2018-04-06 06:57 e50943e8e525197f36f9b4f81464615c063a0a65 go1.10.1 ...
```
the "go1.10.1" shows the go version

(or run/kubectl exec "fortio version"
```
$ fortio version
0.10.1-pre unknown go1.10.1
```

**Comment by thanasisk** [comment]
Please let me know if I need to repeat the runs (maybe with different durations, different parameters etc).

**Comment by ldemailly** [comment]
thx! will close this now as it seems perf is roughly same all the way to 1.15.2
