### ISSUE TITLE
can't disable keepalive

### ISSUE THREAD

**Issue by maxmiles39** [fortio/fortio#343]
Per documents,  keepalive is default to true for http1.1, but no option to disable it. I want to make sure TCP connection is not re-used in my testing.

 -keepalive
        Keep connection alive (only for fast http 1.1) (default true)

**Comment by ldemailly** [comment]
you know reading the [doc](https://github.com/fortio/fortio#command-line-arguments) or -h helps some times:
```
fortio load -keepalive=false www.google.com
...
Sockets used: 44 (for perfect keepalive, would be 4)
```
