### ISSUE TITLE
Data directory using fortio image

### ISSUE THREAD

**Issue by rbkumar88** [fortio/fortio#348]
How can I can access the contents of the -data-dir when run using 
 https://hub.docker.com/r/istio/fortio since it seems to be a scratch image. Doesn't allow me to list or access the data directory.

**Comment by ldemailly** [comment]
if you look at https://hub.docker.com/r/fortio/fortio/dockerfile
you will notice the 
VOLUME /var/lib/fortio
WORKDIR /var/lib/fortio

so that volume can be accessed. or you can browse

ip:8080/data (and /browse in the UI)

eg http://localhost:8080/fortio/data/
