### ISSUE TITLE
[question] How does Fortio behave when connections block?

### ISSUE THREAD

**Issue by rvansa** [fortio/fortio#350]
Hello,

I'd like to ask how Fortio behaves when one or more connections don't return response to the request in relation to the set requests-per-second. Is the qps simply sliced among the connections and if one connection blocks, the other won't do the requests instead, or does it apply some kind of work-stealing?
Does Fortio detect such situation and notify users (invalidate the results) when some request cannot be fired on time?
And btw., are the requests fired strictly on time or is there some variance applied, simulating really random users?

Thank you!

**Comment by ldemailly** [comment]
if one of the N connection hangs/blocks the qps from that connection will fall behind and fortio will not shed load on the other independent threads, if the delay/slow down is temporary or there is an error fortio will try to catch up if there is time left (ie will do back to back requests on that one "bad" connection until the timed run ends to try to reach the target qps)

You can see that with warnings about negative sleep time and the histograms
