### ISSUE TITLE
How to disable warmup?

### ISSUE THREAD

**Issue by dozer47528** [fortio/fortio#358]
I have an API that will process more than 1s.

When I try to test it with this command:

```sh
fortio load -c 1000 -t 30s http://localhost:8080/test
```

It will take more a long time for warmup.

How to disable warmup?

**Comment by ldemailly** [comment]
-c 1000 seems a bit excessive, why do you want so many established simultaneous connections?

if you use `-n count` instead of `-t duration` fortio will do exactly the number of requests requested and thus skip the warmup

**Comment by dozer47528** [comment]
Use `-n` instead of `-t` works for me! Thanks!

I am going to test the performance of my reverse proxy application, which will encounter long requests from upstream.
