### ISSUE TITLE
Question: List Meshery as a fortio adopter?

### ISSUE THREAD

**Issue by leecalcote** [fortio/fortio#359]
Hi @ldemailly, do you have a list of fortio adopters? Would you like to have a small statement added to the fortio.org page highlighting Meshery's adoption of fortio?

fortio will be a point of discussion in the upcoming[Service Mesh Performance working group](https://docs.google.com/presentation/d/1mDE9K8OJ3lyl4GN98Ja3c9ATGWS4rByRtCPIKcoc7LY/edit?usp=sharing).

**Comment by ldemailly** [comment]
good idea, will do

**Comment by ldemailly** [comment]
done, lmk if that works

**Comment by leecalcote** [comment]
@ldemailly that's fantastic. Thank you.

We'll be calling out fortio in this KubeCon EU talk - https://kccnceu20.sched.com/event/Zetg/discreetly-studying-the-effects-of-individual-traffic-control-functions-lee-calcote-layer5?iframe=no&w=100%&sidebar=yes&bg=no
