### ISSUE TITLE
Jitter flag not available in fortio CLI

### ISSUE THREAD

**Issue by nela** [fortio/fortio#360]
Hello,

The `-jitter` flag is listed as on option here in the github documentation, however it is not available in fortio CLI.

`fortio load -k -qps 10 -t 3s -jitter https://fortio.istio.io
flag provided but not defined: -jitter
`
Any way to this without the UI ?

**Comment by olimpias** [comment]
Hi

I guess you are using `fortio v1.3.1`. There is no releases for this jitter change. You need to use master branch to use jitter flag.

**Comment by ldemailly** [comment]
go get -u in the meantime but I will make a 1.4 or 2.0 based on newer go and go modules soon

**Comment by ldemailly** [comment]
available in 1.4.0
