### ISSUE TITLE
No option to keep going despite errors/ -abort-on not respected

### ISSUE THREAD

**Issue by Jiehong** [fortio/fortio#361]
Hello,

I was unable to make fortio continue even if requests result in errors.

I could reproduce it with google for example:

```shell
fortio load -payload '{' -abort-on 500 http://www.google.com/
```

In this case, google answers a 405, and fortio stops right away, even though it should only abort on 500 and not 405.

**Comment by ldemailly** [comment]
you need to use `-allow-initial-errors` as well as the warm up otherwise expects 200

**Comment by Jiehong** [comment]
@ldemailly : that's a strong assumption. I expect some services to send back a percentage of errors when the load is too high, yet I wouldn't expect fortio to abort when this happens.

**Comment by ldemailly** [comment]
if your services are flaky, that’s why -allow-initial-errors exists, but most people don’t want to start a 1h stability and load test if the initial warm up errors out (for instance if there is a typo in the url)
