### ISSUE TITLE
Fortio Server return 503 and then unable to connect during test normal?

### ISSUE THREAD

**Issue by williamyeh** [fortio/fortio#381]
Hi Fortio,

I'm using the benchmark tool under https://github.com/istio/tools/tree/master/perf/benchmark for some performance testing for k8s cluster.

As the test triggered by the python script gradually increases the qps 1000, 2000, then 4000. (see the kubectl command below)

I started to see logs like 
http_client.go:695> Parse non ok code 503, multiple lines.
Followed by,
http-client.go:558> Unable to connect to <Fortio Service IP>:8080 ; dial <Fortio Service IP>:8080: connect: cannot assign requested address. 

At the time when the unable to connect log shows, I saw at least one container in my Fortio Server pod were down. Then it come back up. 
Using the benchmark tool given in the istio/tools repo, my fortio server has 4 pods.

Is this happening because pending queries for fortio server exceeds its limit?
Or is this something that was intended for the fortio clien load test?

kubectl -n someNS exec fortioclient -- fortio load -jitter=False -c 8 -qps 1000 -t 180s -a -r 0.00005 -httpbufferkb=128 http://fortioserver:8080/echo?size=1024
kubectl -n someNS exec fortioclient -- fortio load -jitter=False -c 8 -qps 2000 -t 180s -a -r 0.00005 -httpbufferkb=128 http://fortioserver:8080/echo?size=1024
kubectl -n someNS exec fortioclient -- fortio load -jitter=False -c 8 -qps 4000 -t 180s -a -r 0.00005 -httpbufferkb=128 http://fortioserver:8080/echo?size=1024

Thanks,
William

**Comment by ldemailly** [comment]
That's not expected, thanks for the report.

Do you have the log/reason for the server pod going down?

It looks like the client ran out of file descriptors while trying to reconnect and that's a bit surprising

**Comment by williamyeh** [comment]
Thanks for the response.
I did not get to capture the logs.
Will update if I see them again.

**Comment by ldemailly** [comment]
will close now but reopen if you have more information, thanks!
