### ISSUE TITLE
Fortio loader (client) aborts due to received 404

### ISSUE THREAD

**Issue by georgasa** [fortio/fortio#392]
Hello,

Fortio client aborts because it receives 404 instead of 200: "Aborting because error 404 for http://..." Is it possible to keep sending requests, despite the received error code and do not abort?

Thank you very much,
Apostolos

**Comment by ldemailly** [comment]
404 means not found, is that really what you want to test? you can use -n mode to skip the warm up but fortio's behavior is to make a new connection (as opposed to normal keep alive) when it gets an http error back, so if you're continuously going to get 404 you're going to make a lot of new connections (which is slow)

**Comment by ldemailly** [comment]
use
```
  -allow-initial-errors
    	Allow and don't abort on initial warmup errors
```

if that doesn't resolve your issue please reopen
