### ISSUE TITLE
homebrew formula (MacOS install) needed

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#40]
For people who don't already have go installed, it would be great if someone would create a brew recipe:
https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html

(apparently they don't want the main author to do it, but please update this issue if you contribute one so I can help make sure it works well)

**Comment by ymesika** [comment]
Just to make sure I understand the issue - we want MacOS users to be able to install fortio by simply executing `brew install fortio`?

The new formula will then get dependencies (_go_ and _dep_) and build/install fortio so that it can be run from MacOS terminal.

**Comment by ldemailly** [comment]
yes for `brew install fortio` 

but no, dep is not a dependency and those would be build time, at install and runtime fortio has no dependency 

the hardest and important part is mirroring the version and git magic in Dockerfile and installing the assets

**Comment by ymesika** [comment]
The following is an initial Homebrew formula that installs the fortio along with its assets:

```ruby
class Fortio < Formula
  desc "Fortio (Φορτίο) is load testing tool"
  homepage "https://github.com/istio/fortio"
  url "https://github.com/istio/fortio/archive/v0.8.1.tar.gz"
  sha256 "920943bbac8d1f61857598e018b4aa81f1fe6cfaf06c5bac60620c041cfba859"
  head "https://github.com/istio/fortio.git"

  depends_on "go" => :build
  depends_on "dep" => :build

  def install
    ENV["XC_OS"] = "darwin"
    ENV["XC_ARCH"] = MacOS.prefer_64_bit? ? "amd64" : "386"
    ENV["GOPATH"] = buildpath
    contents = Dir["{*,.git,.gitignore}"]
    (buildpath/"src/istio.io/fortio").install contents
    cd "src/istio.io/fortio" do
      system "dep", "ensure"
      system "go", "build", "-a", "-ldflags", "-s -X istio.io/fortio/ui.resourcesDir=#{lib} -X main.defaultDataDir=#{var}/istio/fortio"
      bin.install "fortio"
      lib.install Dir["ui/static", "ui/templates"]
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fortio --version")
  end
end
```

The relevant _bottles_ will be generated by the CI upon a PR and their references will be injected into the formula. I.e. users who don't want to build (and install dependencies) can simply install the cached bottle (that's the default behavior).

**However**, @ldemailly as you forecasted, mirroring the git magic is a bit more difficult mainly because the initial install is based on the released source tarball which doesn't have the git repo to be based on.

**Comment by ldemailly** [comment]
Thanks for looking into this !

>  desc "Fortio (Φορτίο) is load testing tool"

-> "Fortio is a http and grpc load testing and visualization tool and server"

Do you have access to fortio's git during build ? or alternatively can you checkout only a tagged version and then manually inject the values 

-X istio.io/fortio/version.buildInfo=sha
-X istio.io/fortio/version.tag=tag

For the user command line, let's keep the data dir default unchanged (".") only the static resources (lib dir) is needed

(it's changed to a volume location on docker so it can be mounted/backed up etc... but for a user/interactive, "." like what you get with go get is a good value for the data dir)

**Comment by ymesika** [comment]
I updated the formula to build from a specific tag rather than from a tarball. It's not very common for Homebrew formulas so I can't promise the PR will go smoothly..

```ruby
class Fortio < Formula
  desc "Fortio is a http and grpc load testing and visualization tool and server"
  homepage "https://github.com/istio/fortio"
  #url "https://github.com/istio/fortio/archive/v0.8.1.tar.gz"
  #sha256 "920943bbac8d1f61857598e018b4aa81f1fe6cfaf06c5bac60620c041cfba859"
  head "https://github.com/istio/fortio.git", :tag => "v0.9.0"

  depends_on "go" => :build

  def install
    ENV["XC_OS"] = "darwin"
    ENV["XC_ARCH"] = MacOS.prefer_64_bit? ? "amd64" : "386"
    ENV["GOPATH"] = buildpath
    ENV["CGO_ENABLED"] = "0"
    contents = Dir["{*,.git,.gitignore}"]
    (buildpath/"src/istio.io/fortio").install contents
    cd "src/istio.io/fortio" do
      buildInfo = %x!echo "$(date +'%Y-%m-%d %H:%M') $(git rev-parse HEAD)"!.strip
      tag = %x!echo "$(git describe --tags)"!.strip
      linkFlags = "-s -X istio.io/fortio/ui.resourcesDir=#{lib} "\
        "-X istio.io/fortio/version.tag=#{tag} "\
        "-X \"istio.io/fortio/version.buildInfo=#{buildInfo}\""
      system "go", "build", "-a", "-ldflags", "#{linkFlags}"
      bin.install "fortio"
      lib.install Dir["ui/static", "ui/templates"]
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fortio --version")
  end
end
```

One thing - `git describe --tags` would give back `latest_release` rather than `v0.9.0` because both tags are for the same head. If I change the formula tag to `0.8.1`, for instance, the tag is being set correctly in version.

@ldemailly does it work correctly in docker release for you?
Thanks for your feedback.

**Comment by ymesika** [comment]
A slight update of the ruby to fetch correct tag and use a URL of a Git tag instead of a source tarball.
I believe it's now read for a [Homebrew-core](https://github.com/Homebrew/homebrew-core) PR.

```ruby
class Fortio < Formula
  desc "Fortio is a http and grpc load testing and visualization tool and server"
  homepage "https://github.com/istio/fortio"
  url "https://github.com/istio/fortio.git", :using => :git, :tag => "v0.9.0"
  #sha256 "920943bbac8d1f61857598e018b4aa81f1fe6cfaf06c5bac60620c041cfba859"
  head "https://github.com/istio/fortio.git"

  depends_on "go" => :build

  def install
    ENV["XC_OS"] = "darwin"
    ENV["XC_ARCH"] = MacOS.prefer_64_bit? ? "amd64" : "386"
    ENV["GOPATH"] = buildpath
    ENV["CGO_ENABLED"] = "0"
    contents = Dir["{*,.git,.gitignore}"]
    (buildpath/"src/istio.io/fortio").install contents
    cd "src/istio.io/fortio" do
      buildInfo = %x!echo "$(date +'%Y-%m-%d %H:%M') $(git rev-parse HEAD)"!.strip
      tag = %x!echo "$(git describe --tags --match 'v*')"!.strip
      linkFlags = "-s -X istio.io/fortio/ui.resourcesDir=#{lib} "\
        "-X istio.io/fortio/version.tag=#{tag} "\
        "-X \"istio.io/fortio/version.buildInfo=#{buildInfo}\""
      system "go", "build", "-a", "-ldflags", "#{linkFlags}"
      bin.install "fortio"
      lib.install Dir["ui/static", "ui/templates"]
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fortio --version")
  end
end
```

@ldemailly Please let me know if you want me to submit this PR.

**Comment by ldemailly** [comment]
Thanks for all this work yoshi,

I had a similar issue with docker solved using v* too

How is homebrew usually updating software ?
could we use latest_release for the tag so it auto moves ?

cc me on the pr 

ps: I am in vacation with very poor network this week

**Comment by ldemailly** [comment]
saw the pr, thanks!

what is the output of “fortio version” from that brew recipe produced binary ?

also does fortio server works well/serves the ui correctly ? start fortio server -loglevel debug
and hit localhost:8080/fortio/

thx!

**Comment by ymesika** [comment]
The version will be similar to what you get when you build the docker release. Something like: `0.9.0 2018-04-10 18:48 e50943e8e525197f36f9b4f81464615c063a0a65 go1.10.1`
The only difference is that the date would be the one captured when the bottles were created using their CI system (the create a bottle per MacOS version).

The server works well and UI loads correctly. Once they merge it you are welcome to `brew install fortio` it and let me know if all is well.

**Comment by ldemailly** [comment]
awesome, and what is the process when we have a new tag/release?

**Comment by ymesika** [comment]
Submit a PR with updated formula (just update the tag version and revision).

**Comment by ldemailly** [comment]
homebrew PR is https://github.com/Homebrew/homebrew-core/pull/26653
