### ISSUE TITLE
Modernize the UI theme for fortio Part 1

### ISSUE THREAD

**Issue by timurista** [fortio/fortio#417]
To make fortio UI easier to use, there's a number of UI changes that can help.

1. Fortio is hard to read due to the orange BG first of all. Change the BG to light and use this color scheme: https://coolors.co/47bfff-eea5a5-ffc990-fee5b3-f6f3e1. For buttons, accents. The header can be light orange or blue.

2. Use bootstrap or some kind of framework to give a consistent feel to the UI elements like this: Use a bootstrap or something modern, like this: https://getbootstrap.com/docs/4.5/examples/dashboard/#

3. Also include side panels and use bootstrap or another css theme for inputs on buttons. Panels to switch between browse/comparison and regular mode.

4. Fix alignment of the components so they are flush and spaced evenly.

I can help with this

**Comment by ldemailly** [comment]
Thanks for the suggestions, and most importantly the offer to help!

Some notes:
-For 1) the color scheme comes from being the complementary color from istio's blue - we can tweak/remove the gradient but the logo and orange-ish theme needs to stay (maybe have a dark mode with just the orange backgrounded logo in the corner)
-Also for 1) it also actually work fairly well for the graph / result page
<img width="736" alt="Screen Shot 2020-10-15 at 9 08 52 AM" src="https://user-images.githubusercontent.com/3664595/96156734-45113080-0ec6-11eb-9cf1-185053f33aeb.png">
including it resizing on whichever width the browser is but I agree the start/menu page is ugly
-For 2) I don't want a large framework but if there is a < 10k or so single file CSS that's fine (would be my requirement)
-For 3) depends on 2) and it doesn't have to be super fancy but if something simple is doable, with no dependencies, sounds great
-4) sounds good

**Comment by timurista** [comment]
How's this for a light theme?
![image](https://user-images.githubusercontent.com/4718607/96289736-65122400-0f9a-11eb-984f-b9e909aa2b8c.png)

**Comment by timurista** [comment]
light mode:
![image](https://user-images.githubusercontent.com/4718607/96290227-1c0e9f80-0f9b-11eb-8454-bee5e929fa61.png)

using <10k lib.
https://milligram.io/#getting-started

logo with 3 sails is just css with original istio sail you had

**Comment by ldemailly** [comment]
note, found https://simplecss.org/ which fits also/tbd

**Comment by timurista** [comment]
@ldemailly ah good find that is 4k nice. This issue is quite old, are you still open to modernizing it?
