### ISSUE TITLE
Fortio does not actually run at the specified qps

### ISSUE THREAD

**Issue by minhtrietbkit** [fortio/fortio#419]
=================Basic info=================
* Fortio version: 1.10.0 installed through brew
* Platform: 
  mac OS Mojave 10.14.5 
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
=================Reproduce=================

I want fortio to send 5000 request per seconds to my server for 1 minute. So I use to following cmd

`fortio load -qps 5000 -H "loadtest: true" -t 60s http://mock-up-be.domain.com`

=================Output=================

After running for a minute, fortio exits successfully with following output

```
Fortio 1.10.0 running at 5000 queries per second, 4->4 procs, for 1m0s: http://mock-up-be.domain.com                          
18:21:28 I httprunner.go:82> Starting http test for http://mock-up-be.domain.com with 4 threads at 5000.0 qps                 
Starting at 5000 qps with 4 thread(s) [gomax 4] for 1m0s : 75000 calls each (total 300000)                                     
18:22:31 W periodic.go:509> T003 warning only did 213 out of 75000 calls before reaching 1m0s                                  
18:22:31 I periodic.go:558> T003 ended after 1m0.020510523s : 213 calls. qps=3.5487868754194936
18:22:31 W periodic.go:509> T001 warning only did 213 out of 75000 calls before reaching 1m0s
18:22:31 I periodic.go:558> T001 ended after 1m0.030960246s : 213 calls. qps=3.548169130181333
18:22:31 W periodic.go:509> T002 warning only did 214 out of 75000 calls before reaching 1m0s
18:22:31 I periodic.go:558> T002 ended after 1m0.227511367s : 214 calls. qps=3.553193468280268
18:22:31 W periodic.go:509> T000 warning only did 214 out of 75000 calls before reaching 1m0s
18:22:31 I periodic.go:558> T000 ended after 1m0.246152871s : 214 calls. qps=3.552094030937048
Ended after 1m0.246321516s : 854 calls. qps=14.175
Aggregated Sleep Time : count 854 avg -30.224628 +/- 17.25 min -60.074811888 max -0.269790971 sum -25811.832
# range, mid point, percentile, count
>= -60.0748 <= -0.269791 , -30.1723 , 100.00, 854
# target 50% -30.2074
WARNING 100.00% of sleep were falling behind
Aggregated Function Time : count 854 avg 0.28162378 +/- 0.02461 min 0.248165682 max 0.359788368 sum 240.506711
# range, mid point, percentile, count
>= 0.248166 <= 0.25 , 0.249083 , 0.70, 6
> 0.25 <= 0.3 , 0.275 , 69.32, 586
> 0.3 <= 0.35 , 0.325 , 98.48, 249
> 0.35 <= 0.359788 , 0.354894 , 100.00, 13
# target 50% 0.285922
# target 75% 0.309739
# target 90% 0.335462
# target 99% 0.353358
# target 99.9% 0.359145
Sockets used: 4 (for perfect keepalive, would be 4)
Jitter: false
Code 200 : 854 (100.0 %)
Response Header Sizes : count 854 avg 181.00468 +/- 0.06828 min 181 max 182 sum 154578
Response Body/Total Sizes : count 854 avg 219.00468 +/- 0.06828 min 219 max 220 sum 187030
All done 854 calls (plus 4 warmup) 281.624 ms avg, 14.2 qps
```
=================Expected Output=================

What baffles me is in the end, it reports **All done 854 calls, 14.2 qps**!? Shouldn't this be 5000 * 60 = 300000 and 5000 qps? 14.2 qps actually corresponds to my upstream monitor, which calculates the request rate to my server.

Does this mean that even though I instructed fortio to send request at a constant rate of 5000 qps, somehow fortio ended up sending only at a rate of 14.2 gps?

**Comment by ldemailly** [comment]
it means your server can't do 5k qps with only 8 (the default value you should change using -c, see the faq about settings) connections

Try -qps -1 -c 64 to get an idea of what your service can do, with a 280ms latency you can't hope to do 5k.

**Comment by ldemailly** [comment]
https://github.com/fortio/fortio/wiki/FAQ#i-want-to-get-the-best-results-what-flags-should-i-pass


reopen if you still have questions/issues
