### ISSUE TITLE
Fortio to automatically generate UUID per request and replace it in URL's path.

### ISSUE THREAD

**Issue by artursouza** [fortio/fortio#425]
We use fortio for load testing but it requires a single URL to be used for all requests. In one of the scenarios, we would like part of the URL to be a UUID, this way we can hit the API directly and avoid adding one more HTTP layer to handle the request to fortio and rewrite the URL.

Instead of URL being set in Fortio to  a proxy ("http://localhost:3000/test, for example)" and that proxy forward each request to "https://targetapp/something/{UUID}", Fortio would understand "https://targetapp/something/{UUID}" directly and automatically replace {UUID} with a UUID per request.

I searched the docs and could not find a reference to such feature. Sorry if it already exists and I could not find.

**Comment by ldemailly** [comment]
So there is #409 (ie variable payload is already supported for tcp runner but not yet for http/grpc)

One question though is do you just need unique requests or really an (expensive) UUID?

**Comment by artursouza** [comment]
We don't need uuid for our use case, although I can see how some other applications might need it. Ideally, I think both ways should be supported.
