### ISSUE TITLE
[question] use fortio to test nginx, why the lat(-qps 1000) is more than lat(-qps 0)

### ISSUE THREAD

**Issue by nkuacac** [fortio/fortio#427]
/usr/bin/fortio load -qps 0 -c 64 -t 30s --keepalive=false
keep   rps          avg    p50    p75    p90    p99    p99.9   connections   url                
16     999.97       0.63   0.68   0.84   0.94   0.99   1.00    30016         http://10.0.0.99   
16     35331        0.45   0.62   0.81   0.93   1.00   1.98    1059947       http://10.0.0.99   

keep   rps          avg    p50    p75    p90    p99    p99.9   connections   url
16     999.95       0.54   0.69   0.84   0.94   1.00   1.64    30016         http://172.17.2.2
16     28709        0.56   0.66   0.83   0.93   1.00   1.82    861314        http://172.17.2.2

keep   rps          avg    p50    p75    p90    p99    p99.9   connections   url                  
16     999.96       0.56   0.67   0.84   0.94   1.12   4.08    30016         http://172.17.1.70   
16     38756        0.41   0.64   0.82   0.93   0.99   1.00    1162700       http://172.17.1.70   

keep   rps          avg    p50    p75    p90    p99    p99.9   connections   url                 
16     999.98       0.34   0.63   0.81   0.93   0.99   1.00    30016         http://192.168.5.167
16     53982        0.30   0.61   0.81   0.92   0.99   1.00    1619492       http://192.168.5.167

**Comment by ldemailly** [comment]
Can you post 1 full output for each case? I can't quite make from your listing

One possible guess is if you keep both side hot the kernel on both side keep the processes scheduled while if you drop the qps you get thread context switched away, increasing latency (because they have to wake up from sleep)

Curious though why you force keep alive to be false?

**Comment by nkuacac** [comment]
keep to -c  
 rps to qps (the result)

**Comment by ldemailly** [comment]
going to close this but do reopen if you still have a question. if you do please make sure you:
> Can you post 1 full output for each case? I can't quite make from your listing
