### ISSUE TITLE
fortio/fortio:latest_release is still v1.7

### ISSUE THREAD

**Issue by daixiang0** [fortio/fortio#428]
```
$ docker run fortio/fortio:latest_release version
1.7.1 2020-09-17 18:19 5f4232d7ca0f7429f383f398f4e66cbe6fcaf0d5 go1.15.2
```

**Comment by ldemailly** [comment]
Thanks I was waiting to be sure the last big set of changes were stable but i will move the tag

**Comment by daixiang0** [comment]
@ldemailly maybe both provide `latest_stable` and `latest_release`?

I want to use this tag to use latest release as it occurs on the release page.

**Comment by ldemailly** [comment]
well there is latest already. I very rarely not make a release after significant PR merges, 3 moving tags plus the release one maybe too much, I should maybe just put some timer to move latest_release faster (that was mostly for some istio internal tests/yaml so I didn't have to keep making PRs yet have some control about upgrades)

**Comment by daixiang0** [comment]
I see, istio benchmark test need fortio 1.8+, see https://github.com/istio/istio/issues/27647

**Comment by ldemailly** [comment]
fixed:
$ docker run fortio/fortio:latest_release version
1.11.2 2020-11-19 18:33 1d1ffb103b891e3d2ba62b8ab20974b04f5b0402 go1.15.5
