### ISSUE TITLE
write_record method

### ISSUE THREAD

**Issue by ghost** [fortio/fortio#439]
Hey guys,

I have the following question. I am trying to use write_record method as 
with FortranFile(self.file_path, 'w', header_dtype='>u4', auto_endian=False, check_file=True) as f:
                   f.write_record(self.write_fld)
but for some reasons it writes bogus values into the binary file. Can you please help? The record I am trying to write in is in '>f8' format.

Thannks

**Comment by ldemailly** [comment]
It looks like you opened this issue in the wrong repository!
