### ISSUE TITLE
Question : can data be sent to target via grpc or http post

### ISSUE THREAD

**Issue by vorishirne** [fortio/fortio#457]
Seems like headers are the only way we can pass something to upstream. Also, what about applying conditions based on results of grpc, to control the input data?

**Comment by nkuacac** [comment]
with --content-type support post

**Comment by vorishirne** [comment]
Any docs link @nkuacac ?

**Comment by ldemailly** [comment]
> Seems like headers are the only way we can pass something to upstream. Also, what about applying conditions based on results of grpc, to control the input data?


Can you give an example  of what you would like?

The `payload` is passed to the Ping Server for instance but the Health check doesn't have such argument

The alternative is indeed to make an h2 POST instead of a "grpc" call

**Comment by velcrine** [comment]
I wanted to load test my server. But the issue is my grpc based apis are completely dependent on input data to hit a resource consumption. Seems like this is not possible with Fortio

**Comment by ldemailly** [comment]
> I wanted to load test my server. But the issue is my grpc based apis are completely dependent on input data to hit a resource consumption. Seems like this is not possible with Fortio

It is possible by doing POST of a payload; ie using the http runner vs grpc one
You can even use {{uuid}} in the payload so all requests are unique

**Comment by velcrine** [comment]
Oh let me try thaat. Thanks.
