### ISSUE TITLE
Add Option to Disable IPv6

### ISSUE THREAD

**Issue by ossie-git** [fortio/fortio#458]
I'm currently using the latest version of Fortio:

```
/# fortio --version
1.14.1 2021-01-28 08:02 61f7f962466d35d0eeec397195c4180d4e73b50b go1.15.7
```

and when I tried to access a URL on localhost, it would attempt to connect to it via IPv6 and fail as shown below:

```
/# fortio curl -H "Host: simple-web.example.io" http://localhost:32195/
07:18:22 E http_client.go:647> Unable to connect to [::1]:32195 : dial tcp [::1]:32195: connect: connection refused
07:18:22 E commonflags.go:131> Error status -1 :
```

Once I disabled it by running:

```
/# sysctl -w net.ipv6.conf.all.disable_ipv6=1
```

it would then work fine. It would be great if this option could be added as an option within Fortio. Thanks

**Comment by ldemailly** [comment]
how about just using 127.0.0.1 if you don't want to rely on dns to pick the first address type?

**Comment by ldemailly** [comment]
btw you can also use `-resolve` too  ie
```shell
fortio curl -resolve 127.0.0.1 http://simple-web.example.io:32195/
```
(though then you get `Host: simple-web.example.io:32195` and not `Host: simple-web.example.io`)

going to close this as an answered question

there is a different improvement related to using multiple DNS answers instead of the first one found that would be useful though

**Comment by ldemailly** [comment]
going to add an option to pick ip4, ip6 or both

**Comment by ldemailly** [comment]
@ossie-git thanks for the suggestion, it's now the default in 1.29+

use `-resolve-ip-type ip` or `-resolve-ip-type ip6` to get ipv6 addresses
