### ISSUE TITLE
Not able to install fortio on macbook

### ISSUE THREAD

**Issue by nik131186** [fortio/fortio#46]
Please let me know how to install fortio on MacBook.

I tried brew install fortio as well

**Comment by ldemailly** [comment]
brew recipe needs to be contributed (#40 )


but to install on your mac you just need to install go first then on the terminal type “go get -u istio.io/fortio” like indicated in the README, what happens when you do that ?

**Comment by ldemailly** [comment]
https://github.com/istio/fortio#installation

**Comment by nik131186** [comment]
It worked but not able to find " you can now run fortio (from your gopath bin/ directory)" 

I can find fortio path but not able to execute fortio from MacBook terminal

**Comment by nik131186** [comment]
It worked I need to hit command "./fortio". So that command can execute successfully.

**Comment by ldemailly** [comment]
add
export PATH=$PATH:~/go/bin
to your .bashrc and you will be able to invoke fortio from any shell window

**Comment by ldemailly** [comment]
closing this as resolved! I can reopen if you still have issues

**Comment by nik131186** [comment]
Thanks

Thanks & Regards,
Niket Jaiswal
