### ISSUE TITLE
`Count` in JSON output

### ISSUE THREAD

**Issue by Kn99HN** [fortio/fortio#460]
Hi,

I'm a student and fairly new to load testing. I couldn't find a docs explaining the output of fortio. I ran `fortio load -qps max -t 30s [URL]` and save it as a JSON file. The percentile data makes sense but what exactly does `Count` refer to in the DurationHistogram:

```
{
        "Start": 0.055450266,
        "End": 0.06,
        "Percent": 0.9950248756218906,
        "Count": 2
      },
      {
        "Start": 0.06,
        "End": 0.07,
        "Percent": 4.477611940298507,
        "Count": 7
      },
```

**Comment by ldemailly** [comment]
count is how many samples fall in that bucket
