### ISSUE TITLE
[Question] Json results to summary data

### ISSUE THREAD

**Issue by boeboe** [fortio/fortio#463]
Hi all,

I am looking for some support to get the summary data as reported by the fortio web UI into external systems. The web UI is reporting on (next to QPS) min, avg, p50, p75, p90, p99, p99.9 and max latency results. Unfortunately they are embedded in a PNG together with the histogram, which makes it hard to get them auto exported to an external system (excel in my case). 

I have been looking at the JSON results as well, but they do not contain these summarized latency stats and I cannot figure out how this is calculated based in the data available therein.

Is there a script available that would take fortio JSON results as input and has these latency stats  as output?

Thanks for any insights,
Bart

**Comment by ldemailly** [comment]
it is in the json; it's the percentile section

**Comment by boeboe** [comment]
Oh dear,

I completely missed that because of the scale in sec iso ms. Thanks for helping @ldemailly

**Comment by ldemailly** [comment]
no worries. i was going to dig up the json that does that translation in the ui but got distracted sorry for terse reply. lmk if you still need that/reopen
