### ISSUE TITLE
Fortio vs wrk

### ISSUE THREAD

**Issue by nik131186** [fortio/fortio#47]
Hi,

Could you please explain me how fortio different from wrk in terms of benchmark tool.

I am clear with the parameter of thread but can be change number of connections as a parameter in fortio.

Please explain more in detail about qps(query per second).

**Comment by ldemailly** [comment]
I've added a section to the FAQ:

https://github.com/istio/fortio/wiki/FAQ#how-is-fortio-different-from-wrk

let me know if that answers your question
