### ISSUE TITLE
Path issue in uihandler.go

### ISSUE THREAD

**Issue by juergenzimmermann** [fortio/fortio#474]
Using Windows 10 Enterprise and Fortio 1.16 I get the following error messages:

```
$ fortio.exe server
Fortio 1.16.0 tcp-echo TCP server listening on [::]:8078
...
16:19:07 C uihandler.go:951> Unable to parse main template: open /usr/share/fortio/templates/main.html: Das System kann den angegebenen Pfad nicht finden.
16:19:07 C uihandler.go:956> Unable to parse browse template: open /usr/share/fortio/templates/browse.html: Das System kann den angegebenen Pfad nicht finden.
16:19:07 C uihandler.go:963> Unable to parse sync template: open /usr/share/fortio/templates/sync.html: Das System kann den angegebenen Pfad nicht finden.
...
```

The German error messages can be translated to: _The system cannot find the specified path_.

**Comment by ldemailly** [comment]
@juergenzimmermann  I apologize, I missed a notification for your issue and didn't see it until now.

This looks like it got broken indeed, in the meantime,

if you extracted all the files from the release zip in the same folder (default "extract all" action of windows10 will do the right thing)

```
.\fortio.exe server -static-dir .
```

will work

**Comment by ldemailly** [comment]
it will be fixed in 1.16.1 zip

**Comment by ldemailly** [comment]
Thanks for having taken the time to report the issue

fixed in https://github.com/fortio/fortio/releases/tag/v1.16.1

**Comment by juergenzimmermann** [comment]
@ldemailly Thank you for your efforts! I just tried 1.17.0, and it works fine.

**Comment by ldemailly** [comment]
yw 1.17 is even better as in you can just copy the single exe anywhere and it will have the embedded resources it needs without installation/files/directory dependency
