### ISSUE TITLE
TODOs list

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#48]
Some of the TODO would be good starter tasks:

Current set as of this writing:
```shell
$ git grep TODO
```
```golang
Makefile:# TODO: do something about cyclomatic complexity
fgrpc/grpcrunner.go:// TODO: refactor common parts between http and grpc runners
fgrpc/grpcrunner.go:            // TODO: option to use certs
fhttp/http.go:// Version is the fortio package version (TODO:auto gen/extract).
fhttp/http.go:                  Timeout: 3 * time.Second, // TODO: make configurable
fhttp/http.go:// TODO: refactor - unwiedly/ugly atm
fhttp/http.go:  // TODO: safer to start with -1 and fix ok for http 1.0
fhttp/http.go:          // TODO: need automated tests
fhttp/http.go:                  c.code = ParseDecimal(c.buffer[retcodeOffset : retcodeOffset+3]) //TODO do that only once...
fhttp/http.go:                  // TODO handle 100 Continue
fhttp/http.go:                  // TODO: keep track of list of newlines to efficiently search headers only there
fhttp/http.go:                                          // TODO: just consume the extra instead
fhttp/http.go:          // TODO: this easily lead to contention - use 'thread local'
fhttp/http.go:// TODO: switch to Duration.Round once switched to go 1.9
fhttp/httprunner.go:    // TODO 1. use std client automatically when https url
pingsrv.go:     // TODO doesn't work for ipv6 addrs etc
stats/stats.go:// TODO: consider using an interval search for the last N big buckets
stats/stats.go: // TODO potentially merge despite different offset/scale
stats/stats_test.go:    // TODO: fix the p51 (and p1...), should be 0 not 10
stats/stats_test.go:    tP := []float64{100.} // TODO: use 75 and fix bug
ui/static/js/fortio_chart.js:// TODO: object-ify
ui/static/js/fortio_chart.js:      // TODO may need updateChart() if we persist settings even the first time
ui/templates/browse.html:<p><!-- TODO: find a way to flush/not need two p to get the form visible! -->
ui/templates/main.html:{{end}}{{end}} <!-- 2 extra header lines, TODO: add a JS 'more headers' button -->
ui/uihandler.go:// TODO: auto map from (Http)RunnerOptions to form generation and/or accept
ui/uihandler.go:// TODO: unit tests, allow additional data sets.
ui/uihandler.go:        debugPath = ".." + debugpath // TODO: calculate actual path if not same number of directories
```

**Comment by olimpias** [comment]
I would like to work on this task @ldemailly. Do I need to finish all TODOS or should I select some of them?

**Comment by ldemailly** [comment]
@olimpias fantastic, thank you ! you can just pick 1 at a time! (we can create sub issues if that helps, or just address one or more in a pr)

**Comment by olimpias** [comment]
I think, creating sub task would be great. For now, you can assign me grpcrunner.go, stats.go and stats_test.go related TODO'S as sub-task.

**Comment by ldemailly** [comment]
github has that "feature" that you can't assign issues to people outside the org, so for now consider those "yours" and I am looking forward to your questions and/or PRs

**Comment by olimpias** [comment]
Okay thanks @ldemailly

**Comment by olimpias** [comment]
@ldemailly, May I work on http.go related todos?

**Comment by ldemailly** [comment]
yes, sure, thank you ! but note they are trickier/harder than the others I think (for instance the calc percentile todo left and the other in stats post #61 may be worth looking at)

**Comment by olimpias** [comment]
fhttp/http.go:                  Timeout: 3 * time.Second, // TODO: make configurable
looks easy to me, but I didnt check the code :P.  Okay I will look at them as well :)

**Comment by olimpias** [comment]
@ldemailly  May I still continue with // TODO: use 75 and fix bug and // TODO: consider using an interval search for the last N big buckets?

**Comment by ldemailly** [comment]
yes ! thanks !

**Comment by olimpias** [comment]
Hi @ldemailly . I have  question for // TODO: consider using an interval search for the last N big buckets. If I don't understand you wrong, I need to add new method that allows me to search intervals in Histogram struct and returns Interval array. Input parameter of the method is needed to be a value that is between histogramBucketValues[0] and histogramBucketValues [numValues  -1]. For instance if input value is 4000, I will return bigger values than 4000 from Histogram struct's interval array. If I am wrong, Could you explain TODO in details?

**Comment by ldemailly** [comment]
that todo is about the value->bucket lookup
right now it relies on `val2Bucket` built during init which is a 100,000 entries lookup table
all the values for val2Bucket[75000-10000] are the same (the index of 75000 in histogramBucketValues) which is quite a waste of memory 

It makes sense to make an O(1) lookup for probably the first 5 lines (up to 1000), the rest (12 buckets or so) can be searched  (can be fancy and dichotomy or just simple search)

does this help @olimpias ?

**Comment by olimpias** [comment]
Yes thanks:)

**Comment by olimpias** [comment]
Hi @ldemailly , may I continue my contributions with http 100 support TODO on basic client?

**Comment by olimpias** [comment]
Btw,  we are sending only get request for http in basic client. I googled http 100 code and I find out that server does not send 100 response, unless http request method is put or post. So do we need to really add http  100  code support, If we only use get request. Also If there is a custom request like post method using basic client. Could you write the class name?

**Comment by danehans** [comment]
@ldemailly https://github.com/istio/fortio/pull/116 fixes: `pingsrv.go:     // TODO doesn't work for ipv6 addrs etc`

**Comment by danehans** [comment]
@olimpias can you provide the list of TODOs that you're working on? I want to make sure not to work on the same one's as you.

**Comment by olimpias** [comment]
@danehans I have completed  Timeout: 3 * time.Second, // TODO: make configurable and // TODO potentially merge despite different offset/scale. Also  // TODO: consider using an interval search for the last N big buckets is in PR. I'm not currently working on any TODOS. Please write me which one you will pick.

**Comment by ldemailly** [comment]
unrelated but do you guys want to pull and tell me if you get any issues with the vendor submodule?

**Comment by danehans** [comment]
@ldemailly no vendor submodule issues here:
```
$ make test
/Library/Developer/CommandLineTools/usr/bin/make submodule-sync
git submodule sync
git submodule update --init
Submodule 'vendor' (https://github.com/istio-releases/fortio-vendor.git) registered for path 'vendor'
Cloning into '/Users/daneyonhansen/code/go/src/istio.io/fortio/vendor'...
Submodule path 'vendor': checked out '868e377b7e84ee33278d978602634b7e1eb65145'
go test -timeout 60s -race . ./echosrv ./fgrpc ./fhttp ./fnet ./histogram ./log ./periodic ./stats ./ui
?   	istio.io/fortio	[no test files]
?   	istio.io/fortio/echosrv	[no test files]
ok  	istio.io/fortio/fgrpc	6.303s
ok  	istio.io/fortio/fhttp	17.326s
ok  	istio.io/fortio/fnet	1.025s
?   	istio.io/fortio/histogram	[no test files]
ok  	istio.io/fortio/log	1.027s
ok  	istio.io/fortio/periodic	23.922s
ok  	istio.io/fortio/stats	11.722s
?   	istio.io/fortio/ui	[no test files]
```

**Comment by olimpias** [comment]
// TODO: make it work for port 0 and return the port found and also
// add a non blocking mode that makes sure the socket exists before returning is on PR #155 .

**Comment by olimpias** [comment]
I will start to work on handing http 100 response. Last time, I think, I found handling 100 response from wrong resource. I have found https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html#sec8.2.3. I will try to do things according to this resource.

**Comment by ldemailly** [comment]
> I will start to work on handing http 100 response

let's finish the other 2 first. also I do think you are correct that a server will never send 100 unless the client asks for it - at least my cursory reading of that rfc section

**Comment by ldemailly** [comment]
see also https://github.com/istio/fortio/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by olimpias** [comment]
Okay, After I finish 2, I will give priority to converting binary search from linear in stats.go instead of http 100 response.

**Comment by olimpias** [comment]
I have tested to convert binary search for // TODO: change linear time to O(log(N)) with binary search. But benchmark result were not well for binary search. I think it is because of less number of iteration and variable allocations.
binary search result:100000000           18.8 ns/op
for loop iteartion result:200000000            5.88 ns/op
Tests code are below.
```
func BenchmarkBucketLookupBinary(b *testing.B) {
	slice := histogramBucketValues[maxArrayValueIndex:]
	for i := 0; i < b.N; i++ {
		sort.Search(len(slice), func(i int) bool {
			return slice[i]>99999
		})
	}
}

func BenchmarkBucketLookupIteration(b *testing.B) {
	slice := histogramBucketValues[maxArrayValueIndex:]
	for i := 0; i < b.N; i++ {
		j := 0
		for ;j<len(slice);j++ {
			if slice[j] > 99999 {
				break
			}
		}
	}
}

```
@ldemailly  I think, we should cancel // TODO: change linear time to O(log(N)) with binary search. what do you think?

**Comment by ldemailly** [comment]
@olimpias try SearchInts ? that lambda may be more expensive that needs be

**Comment by olimpias** [comment]
It still is not good. Also I check the inside of SearchInts method. It uses the lambda expession Search method.

**Comment by ldemailly** [comment]
ok thanks, drop that todo then. there are many open issues beside the todos too

**Comment by ldemailly** [comment]
going to close this for now and we can reopen targeted todos
