### ISSUE TITLE
JSON data is mixed up with other output from fortio

### ISSUE THREAD

**Issue by vtymtsiv** [fortio/fortio#480]
### Description

[This line](https://github.com/fortio/fortio/blob/2d52633138d540a33a14d641d7470a998e424c6e/fortio_main.go#L477) prints message mixed with JSON result data. It happens pretty often. 
I'm not familiar with Golang, but looks like it happens because of async output. 

```json
All done 40 calls (plus 4 warmup) 12.010 ms avg, 8.0 qps
{
  "RunType": "HTTP",
  "Labels": "our secret label name",
  "StartTime": "2021-06-01T09:12:40.576422943Z",
  "RequestedQPS": "8",
  "RequestedDuration": "5s",
Successfully wrote 2766 bytes of Json data to stdout
  "ActualQPS": 7.989349663210383,
  "ActualDuration": 5006665334,
  "NumThreads": 4,
```

Initially issue noticed in [fortio-operator](https://github.com/verfio/fortio-operator) repo - https://github.com/verfio/fortio-operator/issues/14

### Problem

When use fortio in [fortio-operator](https://github.com/verfio/fortio-operator), due to fortio-operator implementation, this kind of broken JSON data is stored in ConfigMap, from where UI later reads results.
And since JSON is broken because of `Successfully wrote...` line, the UI could not display the result. 😟

**Comment by ldemailly** [comment]
If you use the option for json to be sent to stdout (- instead of a filename) you need to capture just stdout. what you see is a mix of 2 streams, stdout (json) and stderr (textual informational text)

So it's not a bug, it's just not used properly. Can you point how exactly is fortio invoked in your case?

**Comment by vtymtsiv** [comment]
Hi, thanks for the reply, 
we are using fortio through fortio-operator in order to have automation load testing tool within our Kubernetes cluster.
Due to fortio-operator implementation, it gets json with test result from output and store it in ConfigMap. 
Later that json is read from it by fortio server. And because json is broken, the UI could not visualize it.

**Comment by ldemailly** [comment]
can you point me to the source/config maybe I can spot the bug?

**Comment by ldemailly** [comment]
I looked at the code of that operator and indeed it’s wrong. a (bad?) workaround could be to add `2> /tmp/fortio.log` so stdout json and stderr aren’t mixed up
