### ISSUE TITLE
Question pass auth bearer token

### ISSUE THREAD

**Issue by imalik8088** [fortio/fortio#481]
Hi there, 
I want to load test my api with fortio where I've the following curl command 

`curl "https://example.com/api/services" -H "accept: */*" -H "Authorization: Bearer xxxxxxxxxxx omitted xxxxxxxxx"`

the following fortio command didn't worked for me 

`fortio load -a -c 10 -qps 5 -t 10s -curl -H "accept: */*" -H "Authorization: Bearer " https://example.com/api/services`

> 19:29:13 W http_client.go:146> https requested, switching to standard go client

any idea what I'm doing wrong or is possible at all?

**Comment by ldemailly** [comment]
if you want to do a single curl (to test first it's working as you expect) use
```
fortio curl -H "accept: */*" -H "Authorization: Bearer ..." url
```

Once that works; replace `curl` by `load` and add the other load test params (-c -a -qps -t... but not `-curl`)
