### ISSUE TITLE
Add --uniform mode

### ISSUE THREAD

**Issue by howardjohn** [fortio/fortio#498]
Currently, requests are sent in batches. This is not ideal for testing latency, IMO - neither fortio nor the backend can handle large bursts of requests as well as they could a steady stream. It also is less likely to be indicative of real world scenarios

`-jitter` is a step in the right direction, but still not ideal. It would be ideal if requests were as uniform as possible - for example, if we had 10qps we would send a request a 0, 0.1, 0.2, ... etc, regardless of number of connections.

![2021-05-12_15-51-04](https://user-images.githubusercontent.com/623453/144769265-638c8381-2900-4a52-afa2-8e484252ec4b.png)
The graph above plots every request made by fortio with `-c 128 -qps 128`. There are three groupings: a fork with a `--uniform` implemented and used, defaults, and then jitter.

You can see `-jitter` on its own reduces latency substantially - but the first request is not jittered so we get a spike which skews metrics. Additionally, its still pretty grouped.

Uniform mode shows much more reliable approach.

I have two implementation ideas:
1. For each thread, delay its start based on thread id. This is pretty simple:
```
delaySeconds := float64(perThreadQPS)-(float64(perThreadQPS)/float64(r.NumThreads)*float64(r.NumThreads-id))
start = start.Add(time.Duration(delaySeconds*float64(time.Second)))
```
2. Have a single ticker that triggers the appropriate goroutine to send a request

I have implemented 1 above and it seems to work decently. I am happy to send a PR but wanted to open issue for any discussion

**Comment by howardjohn** [comment]
Uniform:
```
# target 50% 0.00063145
# target 75% 0.000834406
# target 90% 0.00095618
# target 99% 0.00329833
# target 99.9% 0.006958
```

Jitter:
```
# target 50% 0.000658246
# target 75% 0.000885708
# target 90% 0.00138135
# target 99% 0.0157528
# target 99.9% 0.0170924
```

Neither:
```
# target 50% 0.0114178
# target 75% 0.0133344
# target 90% 0.0151864
# target 99% 0.038929
# target 99.9% 0.0431145
```

**Comment by mandarjog** [comment]
Thanks @howardjohn .
nighthawk implements this type of request pacing, so makes sense for fortio too.

cc: @oschaaf

**Comment by oschaaf** [comment]
Nice; that looks like a substantial enhancement to me. Random thought: I think one advantage of implementation approach nr 1. is that its approach may scale across multiple Fortio instances if it would be combined with an option to schedule the start of the load test execution (given synchronized machine clocks) .

**Comment by ldemailly** [comment]
nice work/description (sorry lagging/just catching up)

>  the first request is not jittered so we get a spike which skews metrics

The first request (warm up/connection) is not part of fortio's stats afair

It's a tiny bit of a corner case to use low qps with high connection count as indeed the way fortio works is each thread/connection is independant and it tries to maintain the rate requested inside each of these independent (for scalability) requests (it has other downside that for instance that the catch up after slow request is also individual per connection and not global; to avoid aggregating stats across threads all the time) - but yes that does mean a high -c and low -qps it appears bursty on the server side

All this being said that variant of -jitters sounds good (option 1) with the possibility it still resync if something happen (like network congestion) to resync all the threads

**Comment by howardjohn** [comment]
> The first request (warm up/connection) is not part of fortio's stats afair

I can double check but I believe this was actually not the warmup request, but actually the first request after the warmup. Because we only ever sleep *after* we call our first request in `runOne`, so there is no jitter at all.
