### ISSUE TITLE
Aborting because of rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address localhost:8080/echo?delay=250us:30,5ms:5&status=503:0.5,429:1.5:80: too many colons in address"

### ISSUE THREAD

**Issue by nmarjano** [fortio/fortio#506]
Attempting to run a Fortio Control UI grpc load test but the following error occurs:
Aborting because of rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address localhost:8080/echo?delay=250us:30,5ms:5&status=503:0.5,429:1.5:80: too many colons in address"
Is there some extra configuration required to run this succesfully?
Does fortio support gRPC’s XDS features ?

![Untitled picture](https://user-images.githubusercontent.com/28802522/151339833-0464df91-a9a7-4b17-8eec-94092491ee76.png)

**Comment by ldemailly** [comment]
if you check grpc you have to change the port to match where fortio grpc is running
when you start fortio it tells you:
```
Fortio 1.20.0 grpc 'ping' TCP server listening on [::]:8079
```
so try with 8079 instead of 8080 when checking grpc

**Comment by nmarjano** [comment]
I run the fortio server in following way : 
fortio server &
Fortio 1.19.0 tcp-echo TCP server listening on [::]:8078
Fortio 1.19.0 udp-echo UDP server listening on [::]:8078                                   
Fortio 1.19.0 grpc 'ping' TCP server listening on [::]:8079                                
Fortio 1.19.0 https redirector TCP server listening on [::]:8081                           
Fortio 1.19.0 echo TCP server listening on [::]:8080   

I have also changed the configuration in GUI to match the port:
![Untitled picture](https://user-images.githubusercontent.com/28802522/152031117-bb745038-9160-46bd-bc54-fed89d6ec58e.png)

Terminal Output:
18:46:05 I http_server.go:478> UI: GET /fortio/?labels=Fortio&url=http%3A%2F%2Flocalhost%3A8079%2Fecho%3Fdelay%3D250us%3A30%2C5ms%3A5%26status%3D503%3A0.5%2C429%3A1.5&qps=1000&t=3s&n=&c=8&p=50%2C+75%2C+90%2C+99%2C+99.9&r=0.0001&H=User-Agent%3A+fortio.org%2Ffortio-1.19.0&H=&H=&H=&payload=&resolve=&runner=grpc&grpc-ping-delay=0&save=on&timeout=750ms&load=Start HTTP/1.1 10.252.5.182:63995 ()  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
18:46:05 I uihandler.go:134> Starting grpc load request from 10.252.5.182:63995 for http://localhost:8079/echo?delay=250us:30,5ms:5&status=503:0.5,429:1.5
18:46:05 I uihandler.go:203> New run id 6
18:46:05 I grpcrunner.go:153> Starting GRPC Health test for http://localhost:8079/echo?delay=250us:30,5ms:5&status=503:0.5,429:1.5 with 1*8 threads at 1000.0 qps
18:46:05 I grpcrunner.go:275> stripping http scheme. grpc destination: localhost:8079/echo?delay=250us:30,5ms:5&status=503:0.5,429:1.5: grpc port: 80
18:46:05 E grpcrunner.go:202> Error in first grpc call (ping = false) for http://localhost:8079/echo?delay=250us:30,5ms:5&status=503:0.5,429:1.5: rpc error: code = Unavailable desc = connection closed
18:46:05 E uihandler.go:325> Init error for grpc mode with url http://localhost:8079/echo?delay=250us:30,5ms:5&status=503:0.5,429:1.5 and options {RunType: Runners:[0xc000178000 <nil> <nil> <nil> <nil> <nil> <nil> <nil>] QPS:1000 Duration:3s NumThreads:8 Percentiles:[50 75 90 99 99.9] Resolution:0.0001 Out:0xc00041e960 Labels:Fortio Stop:0xc0003434e0 Exactly:0 Jitter:false RunID:6 Offset:0s} : rpc error: code = Unavailable desc = connection closed

**Comment by ldemailly** [comment]
grpc is just host:port in the url field

**Comment by ldemailly** [comment]
doc/error message could be improved I supposed (PR welcome) - closing for now assuming I answered your question
