### ISSUE TITLE
Unexpected negative sigma

### ISSUE THREAD

**Issue by hans-d** [fortio/fortio#507]
When running `fortio load -qps 0 -c 200 -t 10m -jitter -a http://http-echo:8080`

I get
```
12:33:58 W stats.go:73> Unexpected negative sigma for &{Count:69132101 Min:176 Max:176 Sum:1.2167249776e+10 sumOfSquares:2.141435960576e+12}: -3.5315088282938198e-12
Response Body/Total Sizes : count 69132101 avg 176 +/- 0 min 176 max 176 sum 1.21672498e+10
```

**Comment by ldemailly** [comment]
It's overflowing on the square of size because of 10minutes x 200 connections x maxqps

Either ignore it or run less than 10 minutes

**Comment by ldemailly** [comment]
going to close this assuming I answered your question
