### ISSUE TITLE
invalid UTF-8 character in the generated payload when using gPRC

### ISSUE THREAD

**Issue by Shuanglu** [fortio/fortio#595]
hi team, 
I tried to generate load with grpc. I gave the payload size "1024" to let it generates the payload randomly. However, some bytes 'random' generated cannot be converted to valid utf-8 string. I got the error below.

```
06:28:44 E grpcrunner.go:198> Error in first grpc call (ping = true) for fortioserver:8079: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
```
https://github.com/fortio/fortio/blob/56fa5ab3bb0f93af404e124cf17f3f341450adc4/fnet/network.go#L114   

I guess it may need to add a character set like 'abcdxxxxXYZ' to only include the valid bytes. But not sure how much performance impact there will be.

**Comment by ldemailly** [comment]
Thanks, yes it's a bug. The issue is around the length in bytes vs in utf characters. I should have set the proto type to be bytes instead of string.

**Comment by ldemailly** [comment]
repro:
```
go run . grpcping -payload-size 512 localhost 
19:49:55 E pingsrv.go:121> grpc error from Ping0 rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
exit status 1
```
