### ISSUE TITLE
jrpc - make cleaner error message

### ISSUE THREAD

**Issue by wiardvanrij** [fortio/fortio#633]
I had the following error:

```
2022/10/24 16:21:15 deserialization error, code 404: invalid character '<' looking for beginning of value (raw reply: 54712: <!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"/><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"/><meta...4327a12b80cac28c34f.js\"></script><script nonce=\"\">performance.mark('frontend_boot_js_done_time_seconds');</script></body></html>)
exit status 1
```

This was due to a bug on my end (wrong path to request). Yet I found the error confusing and it took me a while to get it. What would make it more clear/easier is a format like:

```
2022/10/24 16:21:15 deserialization error: invalid character '<' looking for beginning of value 
2022/10/24 16:21:15 request: HTTP code 404
2022/10/24 16:21:15 raw reply: 54712: <!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"/><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"/><meta...4327a12b80cac28c34f.js\"></script><script nonce=\"\">performance.mark('frontend_boot_js_done_time_seconds');</script></body></html>
exit status 1
```

**Comment by ldemailly** [comment]
Can you say what you actually called? because in theory a 404 is intercepted and you get a FetchError in

https://github.com/fortio/fortio/blob/master/jrpc/jrpcClient.go#L165

but maybe it should be closer to https://github.com/fortio/fortio/blob/master/jrpc/jrpcClient.go#L169

a sample repro would help understand your use case

**Comment by ldemailly** [comment]
talked offline, and improving the error message in upcoming pr
