### ISSUE TITLE
Support setting grpc metadata

### ISSUE THREAD

**Issue by ktalg** [fortio/fortio#663]
Now fortio does not support setting grpc [metadata](https://grpc.io/docs/what-is-grpc/core-concepts/#metadata) like '-H' flag in Http Load Generation and it would be better if it did.
I'd be happy to do the work if needed.

**Comment by ldemailly** [comment]
Thanks! Sounds good! MR welcome - hopefully it can be done surgically without requiring too much changes

Can you give an example of what it'd be used for?

Note that we have older packages (server side) that I don't plan on updating yet

**Comment by ktalg** [comment]
> Can you give an example of what it'd be used for?

I'm doing some grpc load testing. There are 2 backend instances and traffic is routed to them via istio consistent hash LB with headers, but I only want to route the request to one of them now (for some reason I can't change any resources) and since I can't add headers (grpc metadata) to the requests now, the request will be randomly routed to both instances(envoy's logic), which is inconvenient.

> Thanks! Sounds good! MR welcome - hopefully it can be done surgically without requiring too much changes

Sure,it may only be necessary to add some code for flag reading and header setting.
