### ISSUE TITLE
grpc client: both user agents are present when set - how to avoid that

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#680]
Somehow both the user speceified user-agent: and the grpc library one are present

```
$ go run . grpcping -loglevel debug -c 1 -n 1 -payload foo -grpc -ping -H fOo:bAr -H host:foo-bar -H user-agent:test123 127.0.0.1:8079
```
yields (`go run . server -loglevel debug&` with my addition to ping srv logging of meta data:
```
15:37:31 V pingsrv.go:48> Ping called {Seq:1 Ts:1673653051146622000 Payload:foo DelayNanos:0} (meta map[:authority:[foo-bar] content-type:[application/grpc] foo:[bAr] user-agent:[test123 grpc-go/1.52.0]])
```

`user-agent:[test123 grpc-go/1.52.0]` instead of just test123

_Originally posted by @ldemailly in https://github.com/fortio/fortio/pull/671#discussion_r1070163152_

**Comment by ktalg** [comment]
This is how grpc-go is implemented.
https://github.com/grpc/grpc-go/blob/78ddc05d9b338930bfa4a0d2b4b5039724b7d013/clientconn.go#L211-L215
 I also looked at other language implementations and found that they all behave similarly, which I think is an implicit format for grpc, according to:
https://github.com/grpc/grpc/issues/2661#issue-97172956

**Comment by ldemailly** [comment]
Thanks! odd choice but ok, maybe then makes sense to have fortio's UA passed unless explicitly removed like for http
