### ISSUE TITLE
Expand FAQ in order to clearly demonstrate which setup is needed in order to contribute

### ISSUE THREAD

**Issue by thanasisk** [fortio/fortio#79]
Hi all,

thanks for the great work done so far. As I understand, fortio is using Golang's canonical imports. This might be confusing to Golang newbies, like me. It would be great to have a section in the FAQ on how someone can fork the repo, setup remotes and start hacking away.

**Comment by ldemailly** [comment]
good idea! thanks for the suggestion!
and now that you figured out (I presume) how to do it, you want to make such a doc PR ;-) ?
(if you don't, no problem, it's fine, I'll check tomorrow)

**Comment by thanasisk** [comment]
Thanks for the positive feedback. To be on the level, currently I am still struggling but once the basic steps are explained, I will be more than happy to expand documentation, if needed.

**Comment by ldemailly** [comment]
What do you think of
https://github.com/istio/fortio/wiki/FAQ#how-do-i-get-started-contributing-to-fortio

**Comment by thanasisk** [comment]
Yep, I am good! Many thanks!
