### ISSUE TITLE
fortio curl context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by gongxh13** [fortio/fortio#798]
Accourding fortio official github introdution, run `fortio curl -stdclient -payload-file sample.json "http://localhost:8080/fortio/rest/run?jsonPath=.metadata" > result.json` command, and I set sample.json as below:
```
{
    "metadata": {
        "url": "localhost:8080",
        "payload": "foo",
        "qps": "40",
        "c": "10",
        "t": "30s",
        "headers": [
            "Foo:Bar",
            "X-Blah: Something else"
        ],
        "save": "on"
    }
}
```
Finally, below error happened:
```
14:49:17.590 I scli.go:107> Starting Φορτίο 1.57.3 h1:kdPlBiws3cFsLcssZxCt2opFmHj14C3yPBokFhMWzmg= go1.20.6 amd64 linux
14:49:20.594 E Unable to send request, method="POST", url="http://localhost:8080/fortio/rest/run?jsonPath=.metadata", err="Post \"http://localhost:8080/fortio/rest/run?jsonPath=.metadata\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)", thread="0", run="0"
14:49:20.594 E Error status -1
```
After 30s, the execute result file generate at disk.

**Comment by gongxh13** [comment]
I solved this problem.
Add `-timeout` parameter in fortio curl command can succeed.

**Comment by ldemailly** [comment]
glad you found it - fortio has many flags so sometimes it can be hard to find (#739)

**Comment by ldemailly** [comment]
@gongxh13 also note there is the `&async=on` you maybe want to use when triggering rest API calls to make them not wait for completion and you can get the result later
