### ISSUE TITLE
add cacert key cert to UI

### ISSUE THREAD

**Issue by t-kruth** [fortio/fortio#865]
is it possible to have the api accept -cacert -key -cert params. I have mounted files and can run the cli command successfully from an exec command to container.

```bash
fortio load -cert /path/to/mounted/file -cacert /path/to/mounted/file -key /path/to/mounted/file <url-to-test>
```
 but would like to be able to set these in the ui and have them be set on the HTTPOptions, possibly set within this 
 
```golang
 func CommonHTTPOptionsFromForm(r *http.Request) *HTTPOptions {
```
https://github.com/fortio/fortio/blob/a95f803d5082c3745ae02315bbc24f1608182009/fhttp/http_utils.go#L635

**Comment by ldemailly** [comment]
You need a different CA in same instance of fortio or would starting the server with a custom CA imply using it for api calls?

**Comment by t-kruth** [comment]
thanks for commenting! awesome project!  I think starting the server with custom cacert/certs/keys to be used for api calls would suffice. I'm assuming this is what's happening when I run the cli with the flags from the server with mounted files. Maybe there's a way to do this now, but anytime is set the flags on start of the server I can't connect

**Comment by ldemailly** [comment]
Thanks for the clarification, I thought I had an issue already that some command line flags don't apply to UI/rapi issued runs, so that should be doable or maybe both

**Comment by ldemailly** [comment]
Btw are you using the UI form or the rapi/ endpoints?

Note that for both there is https-insecure=on already today, but you're trying to do mTLS?

**Comment by ldemailly** [comment]
So I think it's reasonable to have api defaults be from cmdline flags and I think that'd solve it

**Comment by ldemailly** [comment]
Well one problem is today there is only 1 `-cert` and `-key` and it applies contextually to fortio server or client depending in the command. So if you do set `server -cert ...` for instance the UI will start as https server serving that cert

So not sure if after that using the same cert for mtls is... ok?

**Comment by ldemailly** [comment]
Hopefully 1.63.0 (upcoming/shortly) does what you need, please try/confirm

**Comment by t-kruth** [comment]
@ldemailly so does this change mean when starting the `fortio server -cert -key -cacert` I'll be able to navigate to UI.. and the certs only applied to the curl i'm load testing?
