### ISSUE TITLE
Find a metric collection tool for k8s containers

### ISSUE THREAD

**Issue by fawadkhaliq** [fortio/fortio#87]
Need to be able to monitor cpu/memory/diskio for containers and pods

**Comment by fawadkhaliq** [comment]
For container level metrics, there are a few ways/tools:

cAdvisor, Kubelet or node summary API

This is the source of truth for most of the data and it will allow tapping into whatever is/will be exposed via these API. However, you would have to directly interact with these components and require a lot of work on top to gather these stats periodically, store them and expose them in a programatic way or graphically. Not recommended.

Grafana Kubernetes App [2]
 
Uses Intel snap collector [3] to collect stats, comes with a dashboard for container metrics however it does not have a single stable release, is buggy and I am not sure if it is being even actively maintained.  Also, there’s no programatic way of getting metrics. Not recommended.

Heapster [4]

Exposes container metrics via API and  Grafana dashboards. Supported by the k8s community. Supports latest and historical (using influxdb as sink) metrics both. However, recently Heapster has exploded with unmaintained vendor sinks. Few of the problems with Heapster lead to new API definition for metrics and that is called Metrics API and Metrics Server (see below). Also, Heapster API has been marked for deprecation in favor of the Metrics API.

k8s metrics API and metrics server [5]

k8s metrics API are well defined APIs (not implementation) for metrics and canonical implementation of the metrics API is the metrics server [6]. However, it is recently introduced and historical data is missing currently. Only the latest sample is stored and returned by the metrics API. Not aware of any dashboard integration with metrics API/server yet.

Prometheus [7]

Works well with k8s for monitoring. Supports Grafana dashboard for container level metrics too. Disk io metrics are available in prometheus but not exposed to the Grafana dashboard. Programatic way of getting data from prometheus will require work and its better to interface with an API like Metrics API for this.


Recommendation
————————-
Eventually we should use the Metrics API and its future integrations with dashboards to expose the metrics. However, currently, there are only two options that work and have the metrics we are looking for: Heapster and Prometheus. Both have same set of metrics (coming from the same source of truth). Heapster has an API as well that makes it useful for use cases where plotting is not happening on Grafana. For the fastest approach with minimal work, I’d suggest go with Prometheus and add a Grafana dashboards to expose the additional metrics that are missing. 

Heapster usage:
See here: https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md

Prometheus usage
See here: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus

[1] "API_URL:API_PORT/api/v1/proxy/nodes/${NODE}:10255/stats/summary"
[2] https://github.com/grafana/kubernetes-app
[3] http://snap-telemetry.io/
[4] https://github.com/kubernetes/heapster
[5] https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/
[6] https://github.com/kubernetes-incubator/metrics-server
[7] https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus

**Comment by ldemailly** [comment]
This is handled by metrics server and istio etc
