### ISSUE TITLE
permission denied when writing result to json

### ISSUE THREAD

**Issue by xjtupdy** [fortio/fortio#870]
I am tesing Istio Performance by Istio tools(https://github.com/istio/tools/tree/master/perf/benchmark).
But when I execute the command below to generate load in fortio client, 
"python runner/runner.py --conn 2 --qps 1000 --duration 100 --baseline --load_gen_type=fortio --telemetry_mode=v2-nullvm"

I get the error below.
Response Header Sizes : count 100000 avg 167 +/- 0 min 167 max 167 sum 16700000
Response Body/Total Sizes : count 100000 avg 1191 +/- 0 min 1191 max 1191 sum 119100000
All done 100000 calls (plus 2 warmup) 1.310 ms avg, 1000.0 qps
{"ts":1702348400.217665,"level":"fatal","r":1,"file":"fortio_main.go","line":515,"msg":"Unable to create 2023-12-12-023140_8410ea51_qps_1000_c_2_1024_v2_nullvm_both.json: open 2023-12-12-023140_8410ea51_qps_1000_c_2_1024_v2_nullvm_both.json: permission denied"}
panic: aborting...

goroutine 1 [running]:
fortio.org/log.Fatalf({0xb20531?, 0x40?}, {0xc00050f358?, 0xb11954?, 0xb108e4?})
        /build/pkg/mod/fortio.org/log@v1.11.0/logger.go:491 +0x6f
fortio.org/fortio/cli.fortioLoad(0x0, {0xc0000c22d0, 0x5, 0x5}, 0x0)
        /build/pkg/mod/fortio.org/fortio@v1.60.3/cli/fortio_main.go:515 +0x12fe
fortio.org/fortio/cli.FortioMain(0xc0000061a0?)
        /build/pkg/mod/fortio.org/fortio@v1.60.3/cli/fortio_main.go:228 +0x373
main.main()
        /build/pkg/mod/fortio.org/fortio@v1.60.3/main.go:23 +0x1b
command terminated with exit code 2

Environment:
K8S: EKS 1.24
Istio: 1.16.4

Deployment File:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fortioclient
  name: fortioclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortioclient
  template:
    metadata:
      annotations:
        sidecar.istio.io/interceptionMode: REDIRECT
        traffic.sidecar.istio.io/includeOutboundIPRanges: 172.28.0.0/16
        sidecar.istio.io/inject: "true"
        linkerd.io/inject: "disabled"
        # exclude inbound ports of the uncaptured container
        traffic.sidecar.istio.io/excludeInboundPorts: "8076,8077,8078,8081,9999"
        traffic.sidecar.istio.io/excludeOutboundPorts: "80,8076,8077,8078, 8081"
        sidecar.istio.io/proxyCPU: 100m
        sidecar.istio.io/proxyMemory: 128Mi
      labels:
        app: fortioclient
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "fortioserver"
            topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: captured
        securityContext:
          runAsUser: 1
        volumeMounts:
        - name: shared-data
          mountPath: /var/lib/fortio
        image:  fortio/fortio:latest_release
        args:
        - report
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
      - name: shell
        securityContext:
          runAsUser: 1
        volumeMounts:
        - name: shared-data
          mountPath: /var/lib/fortio
        
        image: cfmanteiga/alpine-bash-curl-jq:latest
        args:
        - /bin/sleep
        - 3650d
      - name: uncaptured
        securityContext:
          runAsUser: 1
        image: fortio/fortio:latest_release
        args:
        - report
        - -http-port
        - "8077"
        - -grpc-port
        - "8076"
        - -redirect-port
        - "8081"
        - -tcp-port
        - "8078"
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
---

So how can i solve?

**Comment by ldemailly** [comment]
I am not familiar with what the wrapper script does but the error is pretty straightforward: it means fortio can't write results to the configured directory. Maybe a volume or emptyDir is missing?

**Comment by xjtupdy** [comment]
Yes, you are right. The default temlate chart doesn't have a volume for fortio client. Now it works well. Thank you very much.
