### ISSUE TITLE
add option to restrict listening address

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#91]
that way we can turn `fortio server` into a more secure locally running 'app'

**Comment by danehans** [comment]
@ldemailly let me take a wack at coding this.

**Comment by ldemailly** [comment]
thanks ! let's just address bind address for existing servers and not yet address https

an interesting option (which poses cmd line UI/flags challenges) is how to specify a different bind address for different ports  (redirect vs grpc echo vs echo srv) - I propose we extend the port argument to a string  `[address:]port` ?

**Comment by danehans** [comment]
@ldemailly By extending the port option instead of introducing bind-addr flags, I believe we should rename the port flags to reflect the new meaning. For example: `grpc-endpoint` or `grpc-url`. Thoughts?

**Comment by ldemailly** [comment]
I'm split about keeping flag backward compatibility and naming correctness

let's write the code first and for now keep the flag / tbd
