### ISSUE TITLE
makes qps smoothly 

### ISSUE THREAD

**Issue by nkuacac** [fortio/fortio#912]
* when set  parameter `-qps 1 -c 20 --keepalive=true`, i find the actions is send 20 request then wait 20s. Expect 1 request a second.
* when set parameter `-qps 1 -c 2000  --keepalive=false`, Expect 1 request create 1 connection, and delay close connection

**Comment by ldemailly** [comment]
use `-uniform` if you want to spread the requests for your first example 

your second example is wrong interpretation of -c, -c is the number of concurrent connections, use -c 1 -n 2000 if you want exactly 2000 calls in a single connection

**Comment by nkuacac** [comment]
> use `-uniform` if you want to spread the requests for your first example
> 
> your second example is wrong interpretation of -c, -c is the number of concurrent connections, use -c 1 -n 2000 if you want exactly 2000 calls in a single connection

Thks for reply, second example expect to keep 2000 tcp connections, and 1 qps http request and new connection create.

**Comment by ldemailly** [comment]
what do you see that isn't expected?

**Comment by ldemailly** [comment]
> and delay close connection

not sure what you mean - can you send the output of your run and what happens that you don't expect?

thanks

**Comment by ldemailly** [comment]
please comment and reopen if you still have a question or something isn't working as expected (and apologies I don't understand your second point)

**Comment by nkuacac** [comment]
> what do you see that isn't expected?
 -qps 1 -c 2000  --keepalive=false

I expect 2000 connect will keeping in load balancer.  
We need test keep large connects(not close),  some new connections.  for instance: keeping 1500k connection and 50k/s new connections, 50k requests/s.
