### ISSUE TITLE
Add golangci-lint to tooling

### ISSUE THREAD

**Issue by ccoVeille** [fortio/fortio#945]
I can help to add golangci-lint to fortio.

It could allow to spot errors.

I'm an advanced golangci-lint user. I can also set up GitHub Action for it.

I started working on https://github.com/ccoVeille/golangci-lint-config-examples

I plan to use this and tune tge settings based on your codebase

**Comment by ccoVeille** [comment]
Here is an example of what I did for clipse project


https://github.com/savedra1/clipse/pull/84

**Comment by ldemailly** [comment]
check the actions and makefile, it's already there

**Comment by ldemailly** [comment]
eg https://github.com/fortio/fortio/actions/runs/9727703173/job/26847538916

**Comment by ldemailly** [comment]
my opinionated but quite involved config is https://github.com/fortio/workflows/blob/main/golangci.yml - it includes the key:

fast: false
enable-all: true
disable-all: false

**Comment by ccoVeille** [comment]
Oh, I would have never looked into another repository.

You are really advanced in your golangci-lint usage!

**Comment by ccoVeille** [comment]
I can see a few things that could be added. I will open a PR in fortio/workflow when I will have a few minutes then

**Comment by ldemailly** [comment]
yeah, see `make lint`

going to close this now but yeah if you have some linter config suggestions, feel free! thx!

**Comment by ldemailly** [comment]
you can open an issue with what kind of improvement you're thinking about in
https://github.com/fortio/workflows/issues

I would have "moved" this there but given it says "add golangci-lint" that's been there since day one... a new issue is better

**Comment by ccoVeille** [comment]
Things will happen in

- https://github.com/fortio/workflows/issues/56
