### ISSUE TITLE
New logo for the Fortio project

### ISSUE THREAD

**Issue by craigbox** [fortio/fortio#962]
The Fortio logo uses the Istio sailboat logo, which is now a CNCF trademark.
(Plus, we went to put Fortio on an Istio diagram today and it had too many sailboats. 😁)

Given it's an independent project, can we please select a new logo for Fortio?

I attach a first suggestion generated by DALL-E, with apologies.

![Fortio sample](https://github.com/user-attachments/assets/90145703-a8b9-4143-ac40-28afe9d56ab7)

**Comment by ldemailly** [comment]
well fortio uses something that has multiple sails and the complimentary (orange vs blue) color scheme on purpose because it exercises multiple workloads

hopefully that stays grandfathered or accepted ?

**Comment by craigbox** [comment]
It would be possible, but complicated, to have the LF grant you a license to continue using the trademark.  If you are insistent, we could pursue that.

My point remains that we are unlikely to use this logo on an Istio diagram due to the confusion it entails.

**Comment by ldemailly** [comment]
Not sure I understand fully how a orange logo with 3 sails causes confusion but... ok

Also afaik the sail isn't actually trademarked, just the name "istio"?

Either way the project has used this logo for 7 years so I don't think we should change it (unless forced to... and that would be in poor taste I think)
