### ISSUE TITLE
how to report current qps/status in interval?

### ISSUE THREAD

**Issue by woodgear** [fortio/fortio#980]
if i set a long run duration, there no output in stdout. maybe report the current status in a interval?

**Comment by ldemailly** [comment]
You can use the `-access-log-file` (and format) to log every request and their duration and ingest that in a timeseries DB (like influxdb)

Or use fortiotel variant which sends trace to open telemetry

Or use fortio as a library or script it such as you cut your long running run into smaller segments

Other realtime updates would be #278 / #438
